import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Written out rather than autogenerated, because the order is the reading order:
 * load a model, read a tensor, change one, generate through it.
 *
 * Every doc id is flat — one file, one route segment. `next.config.ts` resolves
 * `/docs/<slug>` to `<slug>.html`, and a nested id would need a second rule.
 */
const sidebars: SidebarsConfig = {
  docs: [
    "index",
    // Ahead of the categories rather than inside Reading: it is the vocabulary
    // every page below writes in, and the first snippet on Capture already uses it.
    "addresses",
    {
      type: "category",
      label: "Models",
      collapsed: false,
      items: ["loading-models", "capabilities"],
    },
    {
      type: "category",
      label: "Reading",
      collapsed: false,
      items: ["capture", "attention", "logit-lens"],
    },
    {
      type: "category",
      label: "Writing",
      collapsed: false,
      items: ["steering"],
    },
    {
      type: "category",
      label: "Generating",
      collapsed: false,
      items: ["generation", "chat"],
    },
    {
      type: "category",
      label: "Serving",
      collapsed: false,
      items: ["async"],
    },
    // Last rather than first, though sizing a machine precedes loading a model on
    // it: everything above is a code sample, and these two are a tool and its
    // endpoint. Somebody reading for the API reaches for the sidebar, not the order.
    {
      type: "category",
      label: "GPU Sizer",
      collapsed: false,
      items: ["gpu-sizer", "gpu-sizer-api"],
    },
  ],
};

export default sidebars;
