"""Render the sizer's inputs into the visualizer's generated data module.

The browser sizer reprices a configuration on every keystroke, so it cannot call this package --
but the two have to agree to the byte, and the way they agree is that only one of them holds the
numbers. The GPU catalog and the calibration constants live in `interp_engine.memory`; this writes
them out as TypeScript, and `visualizer-web/lib/size.ts` holds only arithmetic over what it is given.

`make viz-gpus` rebuilds the file, `make viz-check` fails when it has drifted, and
`visualizer-web/scripts/check-size.ts` is what catches an arithmetic difference rather than a data
one -- it prices the same matrix through both implementations and compares the totals.

The verified records come along for the ride, reduced to the key a badge needs: an option the
harness has actually run on a real card is worth marking as such, and the alternative is the UI
carrying a hand-maintained list that quietly stops matching `gpu-sizer/verified/`.
"""

from __future__ import annotations

import json
import sys
from dataclasses import asdict
from pathlib import Path
from typing import Any

from interp_engine import memory as mem

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "visualizer-web" / "data" / "gpus.generated.ts"
VERIFIED = Path(__file__).resolve().parent / "verified"


def _ts(value: Any) -> str:
    """A Python value as a TypeScript literal.

    `json.dumps` is the right renderer for everything here -- the shapes are numbers, strings,
    booleans and lists of those -- except that JSON has no `undefined`, so `None` arrives as `null`
    and the TypeScript types below say `| null` to match rather than pretending the field is
    optional.
    """
    return json.dumps(value, ensure_ascii=False)


def _gpu_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for spec in mem.GPUS.values():
        row = asdict(spec)
        rows.append(
            {
                "name": row["name"],
                "totalBytes": row["total_bytes"],
                # A tuple in Python, and a two-element tuple in TypeScript too: `supports_fp8` and
                # friends are comparisons against (8, 9) and (10, 0), and those read as comparisons
                # only while the pair is still a pair.
                "computeCapability": list(row["compute_capability"]),
                "bandwidthGibS": row["bandwidth_gib_s"],
                "provenance": row["provenance"],
                "aliases": list(row["aliases"]),
                "eccEnabled": row["ecc_enabled"],
                "notes": row["notes"],
            }
        )
    return rows


def _verified_rows() -> list[dict[str, Any]]:
    """The verified records, one row per run, keyed by what the UI can match on.

    Sorted by file name rather than by date so the output is stable across rebuilds: a diff that
    reorders twelve rows every time the harness runs is a diff nobody reads.
    """
    rows: list[dict[str, Any]] = []
    for path in sorted(VERIFIED.glob("*.json")):
        record = json.loads(path.read_text())
        spec = record.get("spec", {})
        measured = record.get("measured", {})
        rows.append(
            {
                "modelId": record.get("model_id", ""),
                "gpu": record.get("gpu", {}).get("name", ""),
                "backend": record.get("backend", ""),
                "dtype": spec.get("dtype", ""),
                # The three knobs that only ever cost more memory, so one run can speak about a
                # configuration that was never run: a pass vouches for anything asking for no more,
                # a failure condemns anything asking for at least as much. `fit.py`'s `_width` is the
                # same tuple, and `lib/size.ts`'s `evidenceFor` applies the same rule to it.
                "maxModelLen": spec.get("max_model_len", 0),
                "maxNumBatchedTokens": spec.get("max_num_batched_tokens", 0),
                "seqLen": spec.get("seq_len", 0),
                "outcome": record.get("outcome", ""),
                # Not a scoreboard, and the difference is not error. vLLM claims its whole pool
                # whatever it needs, so `peak_bytes` on a passing vLLM run is `card x utilization`
                # while `total_bytes` is what the configuration actually requires -- gpt2 on an A40
                # reads 40.4 against 3.3 GiB, and neither number is wrong. Do not render them as an
                # accuracy comparison.
                "peakBytes": measured.get("peak_bytes", 0),
                "estimatedBytes": record.get("estimate", {}).get("total_bytes", 0),
                "recordedAt": record.get("recorded_at", ""),
            }
        )
    return rows


HEADER = """/**
 * Generated by `python gpu-sizer/publish.py` from `interp_engine.memory` and
 * `gpu-sizer/verified/`. Do not edit: run `make viz-gpus`.
 *
 * Only the inputs live here. `lib/size.ts` holds the arithmetic that spends them, and
 * `scripts/check-size.ts` is what proves the two implementations still agree.
 */

/** One card, as `interp_engine.memory.GpuSpec` knows it. */
export interface Gpu {{
  name: string;
  /** Exact, and what every estimate is weighed against. `totalGib` is for display only. */
  totalBytes: number;
  /** `[major, minor]`, compared as a pair: FP8 needs 8.9, NVFP4 needs 10.0. */
  computeCapability: [number, number];
  bandwidthGibS: number;
  /** How the capacity above is known. Every row is good to about 0.1 GiB. */
  provenance: string;
  aliases: string[];
  /** `null` where the catalog does not know, which is not the same as off. */
  eccEnabled: boolean | null;
  notes: string;
}}

/** One run the harness has really done, reduced to what a badge needs. */
export interface VerifiedRun {{
  modelId: string;
  gpu: string;
  backend: string;
  dtype: string;
  /** The three knobs that only ever cost more memory, ordered against another spec's. */
  maxModelLen: number;
  maxNumBatchedTokens: number;
  seqLen: number;
  /** `"pass"`, or how it failed. A failure is evidence too, and the more important kind. */
  outcome: string;
  /**
   * What the card held and what the estimate asked for. **Not** an accuracy comparison: vLLM claims
   * its whole pool whatever it needs, so a passing vLLM run reads as `card x utilization` against a
   * much smaller requirement, and both numbers are right.
   */
  peakBytes: number;
  estimatedBytes: number;
  recordedAt: string;
}}

export const GPUS: Gpu[] = {gpus};

/**
 * The empirical constants, from `interp_engine.memory.CALIBRATION`. Each one is a measurement with
 * a reason attached; the reasons are in the Python, and changing a value here only makes this file
 * disagree with the engine.
 */
export const CALIBRATION = {calibration} as const;

export const VERIFIED_RUNS: VerifiedRun[] = {verified};
"""


def render() -> str:
    calibration = {key: entry.value if hasattr(entry, "value") else entry for key, entry in mem.CALIBRATION.items()}
    return HEADER.format(
        gpus=json.dumps(_gpu_rows(), indent=2, ensure_ascii=False),
        calibration=json.dumps(calibration, indent=2, ensure_ascii=False),
        verified=json.dumps(_verified_rows(), indent=2, ensure_ascii=False),
    )


def main(argv: list[str]) -> int:
    body = render()
    if "--check" in argv:
        # The committed file is what the browser ships, so a catalog edit that never reached it is a
        # visualizer quoting capacities the engine no longer believes. Same guard `knowledge:check`
        # puts on the docs bundle, and the reason both are checked rather than built during CI.
        current = OUT.read_text() if OUT.exists() else ""
        if current != body:
            print(
                f"{OUT.relative_to(ROOT)} is out of date with interp_engine.memory. Run `make viz-gpus`.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(_gpu_rows())} cards, {len(_verified_rows())} verified runs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
