/**
 * Generated by `python gpu-sizer/publish.py` from `interp_engine.memory` and
 * `gpu-sizer/verified/`. Do not edit: run `make viz-gpus`.
 *
 * Only the inputs live here. `lib/size.ts` holds the arithmetic that spends them, and
 * `scripts/check-size.ts` is what proves the two implementations still agree.
 */

/** One card, as `interp_engine.memory.GpuSpec` knows it. */
export interface Gpu {
  name: string;
  /** Exact, and what every estimate is weighed against. `totalGib` is for display only. */
  totalBytes: number;
  /** `[major, minor]`, compared as a pair: FP8 needs 8.9, NVFP4 needs 10.0. */
  computeCapability: [number, number];
  bandwidthGibS: number;
  /** How the capacity above is known. Every row is good to about 0.1 GiB. */
  provenance: string;
  aliases: string[];
  /** `null` where the catalog does not know, which is not the same as off. */
  eccEnabled: boolean | null;
  notes: string;
}

/** One run the harness has really done, reduced to what a badge needs. */
export interface VerifiedRun {
  modelId: string;
  gpu: string;
  backend: string;
  dtype: string;
  /** The three knobs that only ever cost more memory, ordered against another spec's. */
  maxModelLen: number;
  maxNumBatchedTokens: number;
  seqLen: number;
  /** `"pass"`, or how it failed. A failure is evidence too, and the more important kind. */
  outcome: string;
  /**
   * What the card held and what the estimate asked for. **Not** an accuracy comparison: vLLM claims
   * its whole pool whatever it needs, so a passing vLLM run reads as `card x utilization` against a
   * much smaller requirement, and both numbers are right.
   */
  peakBytes: number;
  estimatedBytes: number;
  recordedAt: string;
}

export const GPUS: Gpu[] = [
  {
    "name": "NVIDIA A40",
    "totalBytes": 47674136985,
    "computeCapability": [
      8,
      6
    ],
    "bandwidthGibS": 696,
    "provenance": "measured (ECC on; nvidia-smi reports 46068 MiB)",
    "aliases": [
      "a40"
    ],
    "eccEnabled": true,
    "notes": "48 GiB board; ECC costs 6.25% of GDDR6, so ECC off gives ~47.4 instead. Cheap and common."
  },
  {
    "name": "NVIDIA RTX A6000",
    "totalBytes": 50895362457,
    "computeCapability": [
      8,
      6
    ],
    "bandwidthGibS": 768,
    "provenance": "measured, but before the A40 ECC correction -- treat as ECC-off",
    "aliases": [
      "a6000",
      "rtx a6000"
    ],
    "eccEnabled": false,
    "notes": ""
  },
  {
    "name": "NVIDIA L40S",
    "totalBytes": 47566762803,
    "computeCapability": [
      8,
      9
    ],
    "bandwidthGibS": 864,
    "provenance": "measured",
    "aliases": [
      "l40s"
    ],
    "eccEnabled": null,
    "notes": "Ada, so the first card in this table with FP8 tensor cores."
  },
  {
    "name": "NVIDIA A100 80GB PCIe",
    "totalBytes": 84932978278,
    "computeCapability": [
      8,
      0
    ],
    "bandwidthGibS": 1935,
    "provenance": "measured",
    "aliases": [
      "a100",
      "a100-80gb",
      "a100 80gb"
    ],
    "eccEnabled": null,
    "notes": ""
  },
  {
    "name": "NVIDIA A100-SXM4-80GB",
    "totalBytes": 84932978278,
    "computeCapability": [
      8,
      0
    ],
    "bandwidthGibS": 2039,
    "provenance": "measured",
    "aliases": [
      "a100-sxm",
      "a100 sxm"
    ],
    "eccEnabled": null,
    "notes": ""
  },
  {
    "name": "NVIDIA A100-SXM4-40GB",
    "totalBytes": 42305427865,
    "computeCapability": [
      8,
      0
    ],
    "bandwidthGibS": 1555,
    "provenance": "spec sheet (40 GiB board) minus the usual driver reservation",
    "aliases": [
      "a100-40gb",
      "a100 40gb"
    ],
    "eccEnabled": null,
    "notes": "The A100 Colab Pro offers."
  },
  {
    "name": "NVIDIA H100 80GB HBM3",
    "totalBytes": 84932978278,
    "computeCapability": [
      9,
      0
    ],
    "bandwidthGibS": 3350,
    "provenance": "spec sheet; same board capacity as the measured A100 80GB",
    "aliases": [
      "h100",
      "h100-sxm",
      "h100 80gb"
    ],
    "eccEnabled": null,
    "notes": "First card here with fast FP8. The one to verify the FP8 rows on."
  },
  {
    "name": "NVIDIA H100 NVL",
    "totalBytes": 99965363814,
    "computeCapability": [
      9,
      0
    ],
    "bandwidthGibS": 3900,
    "provenance": "spec sheet (94 GiB board)",
    "aliases": [
      "h100-nvl",
      "h100 nvl"
    ],
    "eccEnabled": null,
    "notes": ""
  },
  {
    "name": "NVIDIA H200 NVL",
    "totalBytes": 149250113536,
    "computeCapability": [
      9,
      0
    ],
    "bandwidthGibS": 4800,
    "provenance": "measured",
    "aliases": [
      "h200",
      "h200-nvl"
    ],
    "eccEnabled": null,
    "notes": ""
  },
  {
    "name": "NVIDIA B200",
    "totalBytes": 191501854310,
    "computeCapability": [
      10,
      0
    ],
    "bandwidthGibS": 8000,
    "provenance": "measured (ECC on; nvidia-smi reports 183359 MiB, torch 191503007744 bytes)",
    "aliases": [
      "b200"
    ],
    "eccEnabled": true,
    "notes": "Blackwell: NVFP4 in hardware. The engine's published throughput tables were measured here. 192 GB HBM3e, not the 180 GB the marketing sheets quote. Do NOT apply the GDDR6 ECC correction to this row: HBM3e carries ECC on-die, so the 6.25% that costs an A40 3 GiB costs this card nothing, and the measured total above already has ECC enabled."
  },
  {
    "name": "NVIDIA B300",
    "totalBytes": 307090161664,
    "computeCapability": [
      10,
      0
    ],
    "bandwidthGibS": 8000,
    "provenance": "spec sheet (288 GB HBM3e board); unverified",
    "aliases": [
      "b300",
      "blackwell ultra"
    ],
    "eccEnabled": null,
    "notes": ""
  },
  {
    "name": "NVIDIA RTX PRO 6000 Blackwell Server Edition",
    "totalBytes": 101468602368,
    "computeCapability": [
      12,
      0
    ],
    "bandwidthGibS": 1792,
    "provenance": "measured",
    "aliases": [
      "rtx pro 6000",
      "pro 6000",
      "rtx6000"
    ],
    "eccEnabled": null,
    "notes": "96 GiB for roughly a third of an H200's hourly cost, at ~1.8 TB/s against ~4.8."
  },
  {
    "name": "NVIDIA RTX PRO 6000 Blackwell Workstation Edition",
    "totalBytes": 101468602368,
    "computeCapability": [
      12,
      0
    ],
    "bandwidthGibS": 1792,
    "provenance": "inferred from the measured Server Edition; same 96 GiB board, unverified here",
    "aliases": [
      "rtx pro 6000 workstation",
      "pro 6000 workstation"
    ],
    "eccEnabled": null,
    "notes": "Same die and capacity as the Server Edition, which is why it borrows that measurement. The two differ in cooling and power, not memory. A provider hands you whichever the host has, so a config listing one should size against the other too."
  },
  {
    "name": "NVIDIA GeForce RTX 4090",
    "totalBytes": 25340307046,
    "computeCapability": [
      8,
      9
    ],
    "bandwidthGibS": 1008,
    "provenance": "measured",
    "aliases": [
      "4090",
      "rtx 4090"
    ],
    "eccEnabled": null,
    "notes": ""
  },
  {
    "name": "NVIDIA GeForce RTX 5090",
    "totalBytes": 33822867456,
    "computeCapability": [
      12,
      0
    ],
    "bandwidthGibS": 1792,
    "provenance": "spec sheet (32 GiB board)",
    "aliases": [
      "5090",
      "rtx 5090"
    ],
    "eccEnabled": null,
    "notes": ""
  },
  {
    "name": "NVIDIA RTX A5000",
    "totalBytes": 25340307046,
    "computeCapability": [
      8,
      6
    ],
    "bandwidthGibS": 768,
    "provenance": "measured",
    "aliases": [
      "a5000"
    ],
    "eccEnabled": null,
    "notes": ""
  },
  {
    "name": "NVIDIA RTX A4500",
    "totalBytes": 21152713932,
    "computeCapability": [
      8,
      6
    ],
    "bandwidthGibS": 640,
    "provenance": "measured",
    "aliases": [
      "a4500"
    ],
    "eccEnabled": null,
    "notes": ""
  },
  {
    "name": "NVIDIA RTX A4000",
    "totalBytes": 16857746636,
    "computeCapability": [
      8,
      6
    ],
    "bandwidthGibS": 448,
    "provenance": "measured",
    "aliases": [
      "a4000"
    ],
    "eccEnabled": null,
    "notes": ""
  },
  {
    "name": "NVIDIA RTX 4000 Ada Generation",
    "totalBytes": 21152713932,
    "computeCapability": [
      8,
      9
    ],
    "bandwidthGibS": 360,
    "provenance": "measured",
    "aliases": [
      "rtx 4000 ada",
      "4000 ada"
    ],
    "eccEnabled": null,
    "notes": "Ada, so FP8 tensor cores are present where the A4500 it pairs with has none."
  },
  {
    "name": "NVIDIA RTX 2000 Ada Generation",
    "totalBytes": 16857746636,
    "computeCapability": [
      8,
      9
    ],
    "bandwidthGibS": 224,
    "provenance": "measured",
    "aliases": [
      "rtx 2000 ada",
      "2000 ada"
    ],
    "eccEnabled": null,
    "notes": "The smallest card worth serving from: 16 GiB holds an 8B model at bf16 and little else."
  },
  {
    "name": "NVIDIA L4",
    "totalBytes": 23622320128,
    "computeCapability": [
      8,
      9
    ],
    "bandwidthGibS": 300,
    "provenance": "spec sheet (24 GiB board); Colab reports ~22.5 GiB",
    "aliases": [
      "l4"
    ],
    "eccEnabled": null,
    "notes": "Colab's default paid GPU, and what this repo's CI GPU job runs on."
  },
  {
    "name": "Tesla T4",
    "totalBytes": 15676630630,
    "computeCapability": [
      7,
      5
    ],
    "bandwidthGibS": 320,
    "provenance": "spec sheet (16 GiB board); Colab reports 15360 MiB",
    "aliases": [
      "t4",
      "nvidia t4"
    ],
    "eccEnabled": null,
    "notes": "Colab's free tier. Compute 7.5 clears the MXFP4 kernel floor but has no bf16 tensor cores."
  }
];

/**
 * The empirical constants, from `interp_engine.memory.CALIBRATION`. Each one is a measurement with
 * a reason attached; the reasons are in the Python, and changing a value here only makes this file
 * disagree with the engine.
 */
export const CALIBRATION = {
  "cuda_context_gib": 0.6,
  "vllm_overshoot_gib": 0.6,
  "frag_fraction": 0.04,
  "graph_pool_gib": 3.0,
  "eager_workspace_gib": 0.5,
  "hybrid_kv_overhead": 1.1,
  "max_util": 0.9,
  "min_util": 0.1
} as const;

export const VERIFIED_RUNS: VerifiedRun[] = [
  {
    "modelId": "Qwen/Qwen3-4B",
    "gpu": "NVIDIA A40",
    "backend": "eager",
    "dtype": "bfloat16",
    "maxModelLen": 2048,
    "maxNumBatchedTokens": 0,
    "seqLen": 2048,
    "outcome": "pass",
    "peakBytes": 9362735104,
    "estimatedBytes": 11187413606,
    "recordedAt": "2026-08-24T21:52:00Z"
  },
  {
    "modelId": "Qwen/Qwen3-4B",
    "gpu": "NVIDIA A40",
    "backend": "eager",
    "dtype": "bfloat16",
    "maxModelLen": 32768,
    "maxNumBatchedTokens": 0,
    "seqLen": 32752,
    "outcome": "pass",
    "peakBytes": 22962765824,
    "estimatedBytes": 40592511590,
    "recordedAt": "2026-08-24T22:47:14Z"
  },
  {
    "modelId": "Qwen/Qwen3-4B",
    "gpu": "NVIDIA A40",
    "backend": "vllm-static",
    "dtype": "bfloat16",
    "maxModelLen": 8192,
    "maxNumBatchedTokens": 8192,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 45056262144,
    "estimatedBytes": 18693267414,
    "recordedAt": "2026-08-24T21:43:40Z"
  },
  {
    "modelId": "Qwen/Qwen3-4B",
    "gpu": "NVIDIA A40",
    "backend": "vllm",
    "dtype": "bfloat16",
    "maxModelLen": 8192,
    "maxNumBatchedTokens": 2048,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 43711987712,
    "estimatedBytes": 12452143062,
    "recordedAt": "2026-08-24T21:42:30Z"
  },
  {
    "modelId": "Qwen/Qwen3-4B",
    "gpu": "NVIDIA B200",
    "backend": "eager",
    "dtype": "bfloat16",
    "maxModelLen": 2048,
    "maxNumBatchedTokens": 0,
    "seqLen": 2032,
    "outcome": "pass",
    "peakBytes": 9835642880,
    "estimatedBytes": 11172090470,
    "recordedAt": "2026-08-26T01:17:52Z"
  },
  {
    "modelId": "Qwen/Qwen3-4B",
    "gpu": "NVIDIA B200",
    "backend": "vllm-static",
    "dtype": "bfloat16",
    "maxModelLen": 8192,
    "maxNumBatchedTokens": 8192,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 175458222080,
    "estimatedBytes": 24451669318,
    "recordedAt": "2026-08-26T01:17:29Z"
  },
  {
    "modelId": "Qwen/Qwen3-4B",
    "gpu": "NVIDIA B200",
    "backend": "vllm",
    "dtype": "bfloat16",
    "maxModelLen": 8192,
    "maxNumBatchedTokens": 2048,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 174455783424,
    "estimatedBytes": 18210544966,
    "recordedAt": "2026-08-26T01:16:23Z"
  },
  {
    "modelId": "Qwen/Qwen3-4B",
    "gpu": "NVIDIA GeForce RTX 5090",
    "backend": "eager",
    "dtype": "bfloat16",
    "maxModelLen": 2048,
    "maxNumBatchedTokens": 0,
    "seqLen": 2032,
    "outcome": "pass",
    "peakBytes": 9613344768,
    "estimatedBytes": 11172090470,
    "recordedAt": "2026-08-31T23:01:12Z"
  },
  {
    "modelId": "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8",
    "gpu": "NVIDIA B200",
    "backend": "vllm",
    "dtype": "auto",
    "maxModelLen": 8192,
    "maxNumBatchedTokens": 2048,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 174512406528,
    "estimatedBytes": 19112592582,
    "recordedAt": "2026-08-26T01:20:38Z"
  },
  {
    "modelId": "google/gemma-3-12b-pt",
    "gpu": "NVIDIA A40",
    "backend": "eager",
    "dtype": "bfloat16",
    "maxModelLen": 32768,
    "maxNumBatchedTokens": 0,
    "seqLen": 32752,
    "outcome": "oom",
    "peakBytes": 37714132992,
    "estimatedBytes": 216651371334,
    "recordedAt": "2026-08-24T22:26:39Z"
  },
  {
    "modelId": "google/gemma-3-12b-pt",
    "gpu": "NVIDIA A40",
    "backend": "eager",
    "dtype": "bfloat16",
    "maxModelLen": 8192,
    "maxNumBatchedTokens": 0,
    "seqLen": 8176,
    "outcome": "pass",
    "peakBytes": 31179407360,
    "estimatedBytes": 38983766854,
    "recordedAt": "2026-08-24T22:46:25Z"
  },
  {
    "modelId": "google/gemma-3-12b-pt",
    "gpu": "NVIDIA A40",
    "backend": "eager",
    "dtype": "float32",
    "maxModelLen": 2048,
    "maxNumBatchedTokens": 0,
    "seqLen": 2032,
    "outcome": "crash",
    "peakBytes": 0,
    "estimatedBytes": 53399576614,
    "recordedAt": "2026-08-24T22:25:57Z"
  },
  {
    "modelId": "google/gemma-3-12b-pt",
    "gpu": "NVIDIA A40",
    "backend": "vllm-static",
    "dtype": "bfloat16",
    "maxModelLen": 8192,
    "maxNumBatchedTokens": 16384,
    "seqLen": 0,
    "outcome": "crash",
    "peakBytes": 47157608448,
    "estimatedBytes": 46095943862,
    "recordedAt": "2026-08-24T22:28:20Z"
  },
  {
    "modelId": "google/gemma-3-12b-pt",
    "gpu": "NVIDIA A40",
    "backend": "vllm",
    "dtype": "bfloat16",
    "maxModelLen": 8192,
    "maxNumBatchedTokens": 2048,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 43389026304,
    "estimatedBytes": 30795122870,
    "recordedAt": "2026-08-24T21:55:58Z"
  },
  {
    "modelId": "google/gemma-3-12b-pt",
    "gpu": "NVIDIA B200",
    "backend": "eager",
    "dtype": "bfloat16",
    "maxModelLen": 32768,
    "maxNumBatchedTokens": 0,
    "seqLen": 32752,
    "outcome": "oom",
    "peakBytes": 135568293888,
    "estimatedBytes": 216651371334,
    "recordedAt": "2026-08-26T01:24:12Z"
  },
  {
    "modelId": "google/gemma-3-12b-pt",
    "gpu": "NVIDIA B200",
    "backend": "vllm-static",
    "dtype": "bfloat16",
    "maxModelLen": 8192,
    "maxNumBatchedTokens": 262144,
    "seqLen": 0,
    "outcome": "crash",
    "peakBytes": 167294009344,
    "estimatedBytes": 233048278566,
    "recordedAt": "2026-08-26T01:25:35Z"
  },
  {
    "modelId": "google/gemma-3-12b-pt",
    "gpu": "NVIDIA B200",
    "backend": "vllm",
    "dtype": "bfloat16",
    "maxModelLen": 8192,
    "maxNumBatchedTokens": 2048,
    "seqLen": 0,
    "outcome": "crash",
    "peakBytes": 172530597888,
    "estimatedBytes": 36553524774,
    "recordedAt": "2026-08-26T01:19:53Z"
  },
  {
    "modelId": "google/gemma-3-12b-pt",
    "gpu": "NVIDIA GeForce RTX 5090",
    "backend": "eager",
    "dtype": "float32",
    "maxModelLen": 2048,
    "maxNumBatchedTokens": 0,
    "seqLen": 2032,
    "outcome": "oom",
    "peakBytes": 33311162368,
    "estimatedBytes": 53399576614,
    "recordedAt": "2026-08-31T23:00:54Z"
  },
  {
    "modelId": "google/gemma-3-1b-pt",
    "gpu": "NVIDIA A40",
    "backend": "vllm",
    "dtype": "bfloat16",
    "maxModelLen": 4096,
    "maxNumBatchedTokens": 2048,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 44043337728,
    "estimatedBytes": 5308071126,
    "recordedAt": "2026-08-24T22:03:04Z"
  },
  {
    "modelId": "google/gemma-3-1b-pt",
    "gpu": "NVIDIA B200",
    "backend": "vllm",
    "dtype": "bfloat16",
    "maxModelLen": 4096,
    "maxNumBatchedTokens": 2048,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 174778744832,
    "estimatedBytes": 11066473030,
    "recordedAt": "2026-08-26T01:15:50Z"
  },
  {
    "modelId": "nvidia/Llama-3.3-70B-Instruct-FP4",
    "gpu": "NVIDIA B200",
    "backend": "vllm",
    "dtype": "auto",
    "maxModelLen": 8192,
    "maxNumBatchedTokens": 2048,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 175019917312,
    "estimatedBytes": 53008872134,
    "recordedAt": "2026-08-29T06:34:50Z"
  },
  {
    "modelId": "openai-community/gpt2",
    "gpu": "NVIDIA A40",
    "backend": "vllm",
    "dtype": "bfloat16",
    "maxModelLen": 1024,
    "maxNumBatchedTokens": 2048,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 43361763328,
    "estimatedBytes": 3511041494,
    "recordedAt": "2026-08-24T21:40:39Z"
  },
  {
    "modelId": "openai-community/gpt2",
    "gpu": "NVIDIA B200",
    "backend": "vllm",
    "dtype": "bfloat16",
    "maxModelLen": 1024,
    "maxNumBatchedTokens": 1024,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 174030061568,
    "estimatedBytes": 9269443398,
    "recordedAt": "2026-08-26T01:15:02Z"
  },
  {
    "modelId": "openai/gpt-oss-20b",
    "gpu": "NVIDIA A40",
    "backend": "vllm",
    "dtype": "auto",
    "maxModelLen": 4096,
    "maxNumBatchedTokens": 2048,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 43122688000,
    "estimatedBytes": 17161838678,
    "recordedAt": "2026-08-24T21:53:45Z"
  },
  {
    "modelId": "openai/gpt-oss-20b",
    "gpu": "NVIDIA B200",
    "backend": "vllm",
    "dtype": "auto",
    "maxModelLen": 4096,
    "maxNumBatchedTokens": 2048,
    "seqLen": 0,
    "outcome": "pass",
    "peakBytes": 173585465344,
    "estimatedBytes": 22920240582,
    "recordedAt": "2026-08-26T01:18:39Z"
  }
];
