/**
 * Generated by `npx tsx scripts/build-model-cache.ts`. Do not edit: run `make viz-models`.
 *
 * Facts only. The arithmetic that spends them is `lib/size.ts`, which reprices on every control
 * change, so caching a fit would cache the one thing that is never reused.
 *
 * Resolved with a token, which is why the gated repos here carry trunk dims. What is stored is
 * dimensions and byte counts — nothing a model card does not already say.
 */

import type { ModelMemoryFacts } from "@/lib/hub";

export interface CachedModel {
  facts: ModelMemoryFacts;
  /** The repo revision these facts were read from, for `--check` to compare against. */
  sha: string;
}

export const GENERATED_AT = "2026-09-01T06:19:42.023Z";

/** Keyed by lowercased model id; `facts.modelId` keeps the canonical spelling. */
export const MODEL_CACHE: Record<string, CachedModel> = {
  "allenai/olmo-2-0425-1b": {
    "facts": {
      "modelId": "allenai/OLMo-2-0425-1B",
      "weights": {
        "paramCount": 1484916736,
        "onDiskBytes": 5939666944,
        "storedDtype": "float32",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "F32": 1484916736
        },
        "source": "safetensors-index"
      },
      "nLayers": 16,
      "dModel": 2048,
      "nHeads": 16,
      "nKvHeads": 16,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 100352,
      "intermediateSize": 8192,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 4096,
      "architecture": "Olmo2ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 128, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "a1847dff35000b4271fa70afc5db10fd29fedbdf"
  },
  "allenai/olmo-3-1025-7b": {
    "facts": {
      "modelId": "allenai/Olmo-3-1025-7B",
      "weights": {
        "paramCount": 7298011136,
        "onDiskBytes": 14596022272,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 7298011136
        },
        "source": "safetensors-index"
      },
      "nLayers": 32,
      "dModel": 4096,
      "nHeads": 32,
      "nKvHeads": 32,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 100278,
      "intermediateSize": 11008,
      "nExperts": 0,
      "layerTypes": [
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention"
      ],
      "slidingWindow": 4096,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 65536,
      "architecture": "Olmo3ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 128, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "a81bae42db3975be1671e27b9c9a56da1a9f980f"
  },
  "allenai/olmo-3-1125-32b": {
    "facts": {
      "modelId": "allenai/Olmo-3-1125-32B",
      "weights": {
        "paramCount": 32233522176,
        "onDiskBytes": 64467044352,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 32233522176
        },
        "source": "safetensors-index"
      },
      "nLayers": 64,
      "dModel": 5120,
      "nHeads": 40,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 100278,
      "intermediateSize": 27648,
      "nExperts": 0,
      "layerTypes": [
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention"
      ],
      "slidingWindow": 4096,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 65536,
      "architecture": "Olmo3ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 128, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "c2b61dae89a1ad10e4ad5653d0e46b590902607b"
  },
  "bigcode/gpt_bigcode-santacoder": {
    "facts": {
      "modelId": "bigcode/gpt_bigcode-santacoder",
      "weights": {
        "paramCount": 1124886528,
        "onDiskBytes": 2249803464,
        "storedDtype": "",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "F16": 1124886528
        },
        "source": "file-sizes"
      },
      "nLayers": 24,
      "dModel": 2048,
      "nHeads": 16,
      "nKvHeads": 1,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 49280,
      "intermediateSize": 8192,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 2048,
      "architecture": "GPTBigCodeForCausalLM",
      "derivedDims": [
        "head_dim"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim, so it was derived as hidden_size / num_attention_heads. Some families set a different value in their model class (gemma-3-12b's is 256 where the division gives 240), and a derived value that is too small UNDER-states the KV cache."
      ]
    },
    "sha": "291931872cae83498cf984b16319f47f5e9e7a07"
  },
  "bigcode/starcoder2-3b": {
    "facts": {
      "modelId": "bigcode/starcoder2-3b",
      "weights": {
        "paramCount": 3030371328,
        "onDiskBytes": 12121539344,
        "storedDtype": "",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "F32": 3030371328
        },
        "source": "file-sizes"
      },
      "nLayers": 30,
      "dModel": 3072,
      "nHeads": 24,
      "nKvHeads": 2,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 49152,
      "intermediateSize": 12288,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 4096,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 16384,
      "architecture": "Starcoder2ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 128, so the KV figures are exact rather than derived from hidden_size / heads.",
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "733247c55e3f73af49ce8e9c7949bf14af205928"
  },
  "bigscience/bloom-560m": {
    "facts": {
      "modelId": "bigscience/bloom-560m",
      "weights": {
        "paramCount": 559214592,
        "onDiskBytes": 1118459525,
        "storedDtype": "",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "F16": 559214592
        },
        "source": "file-sizes"
      },
      "nLayers": 24,
      "dModel": 1024,
      "nHeads": 16,
      "nKvHeads": 16,
      "headDim": 64,
      "vHeadDim": 64,
      "vocabSize": 250880,
      "intermediateSize": 4096,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 0,
      "architecture": "BloomForCausalLM",
      "derivedDims": [
        "head_dim",
        "max_position_embeddings"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim, so it was derived as hidden_size / num_attention_heads. Some families set a different value in their model class (gemma-3-12b's is 256 where the division gives 240), and a derived value that is too small UNDER-states the KV cache.",
        "config.json omits max_position_embeddings, so the model's advertised context is unknown and a max_model_len has to be chosen rather than defaulted."
      ]
    },
    "sha": "ac2ae5fab2ce3f9f40dc79b5ca9f637430d24971"
  },
  "deepseek-ai/deepseek-v2-lite": {
    "facts": {
      "modelId": "deepseek-ai/DeepSeek-V2-Lite",
      "weights": {
        "paramCount": 15706484224,
        "onDiskBytes": 31412968448,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 15706484224
        },
        "source": "safetensors-index"
      },
      "nLayers": 27,
      "dModel": 2048,
      "nHeads": 16,
      "nKvHeads": 16,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 102400,
      "intermediateSize": 10944,
      "nExperts": 64,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 163840,
      "architecture": "DeepseekV2ForCausalLM",
      "derivedDims": [
        "head_dim"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim, so it was derived as hidden_size / num_attention_heads. Some families set a different value in their model class (gemma-3-12b's is 256 where the division gives 240), and a derived value that is too small UNDER-states the KV cache."
      ]
    },
    "sha": "604d5664dddd88a0433dbae533b7fe9472482de0"
  },
  "deepseek-ai/deepseek-v4-flash": {
    "facts": {
      "modelId": "deepseek-ai/DeepSeek-V4-Flash",
      "weights": {
        "paramCount": 290944616402,
        "onDiskBytes": 159609485896,
        "storedDtype": "bfloat16",
        "quantMethod": "fp8",
        "expertDtype": "fp4",
        "elementsByDtype": {
          "BF16": 1415259264,
          "F32": 36168018,
          "F8_E4M3": 6023020544,
          "I64": 2327040,
          "I8": 283467841536
        },
        "source": "safetensors-index"
      },
      "nLayers": 43,
      "dModel": 4096,
      "nHeads": 64,
      "nKvHeads": 1,
      "headDim": 512,
      "vHeadDim": 512,
      "vocabSize": 129280,
      "intermediateSize": 2048,
      "nExperts": 256,
      "layerTypes": null,
      "slidingWindow": 128,
      "nResidualStreams": 4,
      "maxPositionEmbeddings": 1048576,
      "architecture": "DeepseekV4ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "60d8d70770c6776ff598c94bb586a859a38244f1"
  },
  "deepseek-ai/deepseek-v4-flash-0731": {
    "facts": {
      "modelId": "deepseek-ai/DeepSeek-V4-Flash-0731",
      "weights": {
        "paramCount": 304180418494,
        "onDiskBytes": 166878536440,
        "storedDtype": "bfloat16",
        "quantMethod": "fp8",
        "expertDtype": "fp4",
        "elementsByDtype": {
          "BF16": 1483567488,
          "F32": 37741630,
          "F8_E4M3": 6304038912,
          "I64": 2327040,
          "I8": 296352743424
        },
        "source": "safetensors-index"
      },
      "nLayers": 43,
      "dModel": 4096,
      "nHeads": 64,
      "nKvHeads": 1,
      "headDim": 512,
      "vHeadDim": 512,
      "vocabSize": 129280,
      "intermediateSize": 2048,
      "nExperts": 256,
      "layerTypes": null,
      "slidingWindow": 128,
      "nResidualStreams": 4,
      "maxPositionEmbeddings": 1048576,
      "architecture": "DeepseekV4ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "7872f01b1d1fe23eabc4c98b48bffcef5a386062"
  },
  "eleutherai/pythia-70m-deduped": {
    "facts": {
      "modelId": "EleutherAI/pythia-70m-deduped",
      "weights": {
        "paramCount": 95592496,
        "onDiskBytes": 166029852,
        "storedDtype": "float16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "F16": 70426672,
          "U8": 25165824
        },
        "source": "file-sizes"
      },
      "nLayers": 6,
      "dModel": 512,
      "nHeads": 8,
      "nKvHeads": 8,
      "headDim": 64,
      "vHeadDim": 64,
      "vocabSize": 50304,
      "intermediateSize": 2048,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 2048,
      "architecture": "GPTNeoXForCausalLM",
      "derivedDims": [
        "head_dim"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim, so it was derived as hidden_size / num_attention_heads. Some families set a different value in their model class (gemma-3-12b's is 256 where the division gives 240), and a derived value that is too small UNDER-states the KV cache."
      ]
    },
    "sha": "e93a9faa9c77e5d09219f6c868bfc7a1bd65593c"
  },
  "facebook/opt-125m": {
    "facts": {
      "modelId": "facebook/opt-125m",
      "weights": {
        "paramCount": 190464000,
        "onDiskBytes": 380928000,
        "storedDtype": "float16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {},
        "source": "config-count"
      },
      "nLayers": 12,
      "dModel": 768,
      "nHeads": 12,
      "nKvHeads": 12,
      "headDim": 64,
      "vHeadDim": 64,
      "vocabSize": 50272,
      "intermediateSize": 3072,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 2048,
      "architecture": "OPTForCausalLM",
      "derivedDims": [
        "head_dim"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim, so it was derived as hidden_size / num_attention_heads. Some families set a different value in their model class (gemma-3-12b's is 256 where the division gives 240), and a derived value that is too small UNDER-states the KV cache.",
        "no shard metadata was readable, so the weight figure is counted from the config dims. It omits norms, biases and quantization scales, so treat it as a floor."
      ]
    },
    "sha": "27dcfa74d334bc871f3234de431e71c6eeba5dd6"
  },
  "google/gemma-2-27b": {
    "facts": {
      "modelId": "google/gemma-2-27b",
      "weights": {
        "paramCount": 27227128320,
        "onDiskBytes": 108908513280,
        "storedDtype": "float32",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "F32": 27227128320
        },
        "source": "safetensors-index"
      },
      "nLayers": 46,
      "dModel": 4608,
      "nHeads": 32,
      "nKvHeads": 16,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 256000,
      "intermediateSize": 36864,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 4096,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 8192,
      "architecture": "Gemma2ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "938270f5272feb02779b55c2bb2fffdd0f53ff0c"
  },
  "google/gemma-2-2b": {
    "facts": {
      "modelId": "google/gemma-2-2b",
      "weights": {
        "paramCount": 2614341888,
        "onDiskBytes": 10457367552,
        "storedDtype": "float32",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "F32": 2614341888
        },
        "source": "safetensors-index"
      },
      "nLayers": 26,
      "dModel": 2304,
      "nHeads": 8,
      "nKvHeads": 4,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 256000,
      "intermediateSize": 9216,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 4096,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 8192,
      "architecture": "Gemma2ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "c5ebcd40d208330abc697524c919956e692655cf"
  },
  "google/gemma-2-2b-it": {
    "facts": {
      "modelId": "google/gemma-2-2b-it",
      "weights": {
        "paramCount": 2614341888,
        "onDiskBytes": 5228683776,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 2614341888
        },
        "source": "safetensors-index"
      },
      "nLayers": 26,
      "dModel": 2304,
      "nHeads": 8,
      "nKvHeads": 4,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 256000,
      "intermediateSize": 9216,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 4096,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 8192,
      "architecture": "Gemma2ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "299a8560bedf22ed1c72a8a11e7dce4a7f9f51f8"
  },
  "google/gemma-2-9b": {
    "facts": {
      "modelId": "google/gemma-2-9b",
      "weights": {
        "paramCount": 9241705984,
        "onDiskBytes": 36966823936,
        "storedDtype": "float32",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "F32": 9241705984
        },
        "source": "safetensors-index"
      },
      "nLayers": 42,
      "dModel": 3584,
      "nHeads": 16,
      "nKvHeads": 8,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 256000,
      "intermediateSize": 14336,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 4096,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 8192,
      "architecture": "Gemma2ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "33c193028431c2fde6c6e51f29e6f17b60cbfac6"
  },
  "google/gemma-2-9b-it": {
    "facts": {
      "modelId": "google/gemma-2-9b-it",
      "weights": {
        "paramCount": 9241705984,
        "onDiskBytes": 18483411968,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 9241705984
        },
        "source": "safetensors-index"
      },
      "nLayers": 42,
      "dModel": 3584,
      "nHeads": 16,
      "nKvHeads": 8,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 256000,
      "intermediateSize": 14336,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 4096,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 8192,
      "architecture": "Gemma2ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "11c9b309abf73637e4b6f9a3fa1e92e615547819"
  },
  "google/gemma-3-12b-it": {
    "facts": {
      "modelId": "google/gemma-3-12b-it",
      "weights": {
        "paramCount": 12187325040,
        "onDiskBytes": 24374650080,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 12187325040
        },
        "source": "safetensors-index"
      },
      "nLayers": 48,
      "dModel": 3840,
      "nHeads": 16,
      "nKvHeads": 8,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 262208,
      "intermediateSize": 15360,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 1024,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 0,
      "architecture": "Gemma3ForConditionalGeneration",
      "derivedDims": [
        "max_position_embeddings",
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "config.json states no vocab_size, so it was read from the checkpoint: the embedding matrix is 262,208 rows. This is the term the eager logits are priced from, and pricing it at zero is the direction that hides an OOM.",
        "config.json omits head_dim; the key projection in the checkpoint gives 256, so the KV figures are exact rather than derived from hidden_size / heads.",
        "config.json omits max_position_embeddings, so the model's advertised context is unknown and a max_model_len has to be chosen rather than defaulted.",
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "96b6f1eccf38110c56df3a15bffe176da04bfd80"
  },
  "google/gemma-3-12b-pt": {
    "facts": {
      "modelId": "google/gemma-3-12b-pt",
      "weights": {
        "paramCount": 12187325040,
        "onDiskBytes": 24374650080,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 12187325040
        },
        "source": "safetensors-index"
      },
      "nLayers": 48,
      "dModel": 3840,
      "nHeads": 16,
      "nKvHeads": 8,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 262208,
      "intermediateSize": 15360,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 1024,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 0,
      "architecture": "Gemma3ForConditionalGeneration",
      "derivedDims": [
        "max_position_embeddings",
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "config.json states no vocab_size, so it was read from the checkpoint: the embedding matrix is 262,208 rows. This is the term the eager logits are priced from, and pricing it at zero is the direction that hides an OOM.",
        "config.json omits head_dim; the key projection in the checkpoint gives 256, so the KV figures are exact rather than derived from hidden_size / heads.",
        "config.json omits max_position_embeddings, so the model's advertised context is unknown and a max_model_len has to be chosen rather than defaulted.",
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "295efb63d01a7017928f273a94ebb86105c9526f"
  },
  "google/gemma-3-1b-it": {
    "facts": {
      "modelId": "google/gemma-3-1b-it",
      "weights": {
        "paramCount": 999885952,
        "onDiskBytes": 1999811208,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 999885952
        },
        "source": "file-sizes"
      },
      "nLayers": 26,
      "dModel": 1152,
      "nHeads": 4,
      "nKvHeads": 1,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 262144,
      "intermediateSize": 6912,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 512,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 32768,
      "architecture": "Gemma3ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "dcc83ea841ab6100d6b47a070329e1ba4cf78752"
  },
  "google/gemma-3-1b-pt": {
    "facts": {
      "modelId": "google/gemma-3-1b-pt",
      "weights": {
        "paramCount": 999885952,
        "onDiskBytes": 1999811208,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 999885952
        },
        "source": "file-sizes"
      },
      "nLayers": 26,
      "dModel": 1152,
      "nHeads": 4,
      "nKvHeads": 1,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 262144,
      "intermediateSize": 6912,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 512,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 32768,
      "architecture": "Gemma3ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "fcf18a2a879aab110ca39f8bffbccd5d49d8eb29"
  },
  "google/gemma-3-270m": {
    "facts": {
      "modelId": "google/gemma-3-270m",
      "weights": {
        "paramCount": 268098176,
        "onDiskBytes": 536223056,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 268098176
        },
        "source": "file-sizes"
      },
      "nLayers": 18,
      "dModel": 640,
      "nHeads": 4,
      "nKvHeads": 1,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 262144,
      "intermediateSize": 2048,
      "nExperts": 0,
      "layerTypes": [
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention"
      ],
      "slidingWindow": 512,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 32768,
      "architecture": "Gemma3ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "9b0cfec892e2bc2afd938c98eabe4e4a7b1e0ca1"
  },
  "google/gemma-3-270m-it": {
    "facts": {
      "modelId": "google/gemma-3-270m-it",
      "weights": {
        "paramCount": 268098176,
        "onDiskBytes": 536223056,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 268098176
        },
        "source": "file-sizes"
      },
      "nLayers": 18,
      "dModel": 640,
      "nHeads": 4,
      "nKvHeads": 1,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 262144,
      "intermediateSize": 2048,
      "nExperts": 0,
      "layerTypes": [
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention"
      ],
      "slidingWindow": 512,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 32768,
      "architecture": "Gemma3ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "ac82b4e820549b854eebf28ce6dedaf9fdfa17b3"
  },
  "google/gemma-3-27b-it": {
    "facts": {
      "modelId": "google/gemma-3-27b-it",
      "weights": {
        "paramCount": 27432406640,
        "onDiskBytes": 54864813280,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 27432406640
        },
        "source": "safetensors-index"
      },
      "nLayers": 62,
      "dModel": 5376,
      "nHeads": 32,
      "nKvHeads": 16,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 262208,
      "intermediateSize": 21504,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 1024,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 0,
      "architecture": "Gemma3ForConditionalGeneration",
      "derivedDims": [
        "max_position_embeddings",
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "config.json states no vocab_size, so it was read from the checkpoint: the embedding matrix is 262,208 rows. This is the term the eager logits are priced from, and pricing it at zero is the direction that hides an OOM.",
        "config.json omits max_position_embeddings, so the model's advertised context is unknown and a max_model_len has to be chosen rather than defaulted.",
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "005ad3404e59d6023443cb575daa05336842228a"
  },
  "google/gemma-3-27b-pt": {
    "facts": {
      "modelId": "google/gemma-3-27b-pt",
      "weights": {
        "paramCount": 27432406640,
        "onDiskBytes": 54864813280,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 27432406640
        },
        "source": "safetensors-index"
      },
      "nLayers": 62,
      "dModel": 5376,
      "nHeads": 32,
      "nKvHeads": 16,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 262208,
      "intermediateSize": 21504,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 1024,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 0,
      "architecture": "Gemma3ForConditionalGeneration",
      "derivedDims": [
        "max_position_embeddings",
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "config.json states no vocab_size, so it was read from the checkpoint: the embedding matrix is 262,208 rows. This is the term the eager logits are priced from, and pricing it at zero is the direction that hides an OOM.",
        "config.json omits max_position_embeddings, so the model's advertised context is unknown and a max_model_len has to be chosen rather than defaulted.",
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "9fe3c4ebc93fbadb14913801536d022054ef11cc"
  },
  "google/gemma-3-4b-it": {
    "facts": {
      "modelId": "google/gemma-3-4b-it",
      "weights": {
        "paramCount": 4300079472,
        "onDiskBytes": 8600158944,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 4300079472
        },
        "source": "safetensors-index"
      },
      "nLayers": 34,
      "dModel": 2560,
      "nHeads": 0,
      "nKvHeads": 0,
      "headDim": 0,
      "vHeadDim": 0,
      "vocabSize": 262208,
      "intermediateSize": 10240,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 1024,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 0,
      "architecture": "Gemma3ForConditionalGeneration",
      "derivedDims": [
        "max_position_embeddings",
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "config.json states no vocab_size, so it was read from the checkpoint: the embedding matrix is 262,208 rows. This is the term the eager logits are priced from, and pricing it at zero is the direction that hides an OOM.",
        "config.json omits max_position_embeddings, so the model's advertised context is unknown and a max_model_len has to be chosen rather than defaulted.",
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "093f9f388b31de276ce2de164bdc2081324b9767"
  },
  "google/gemma-3-4b-pt": {
    "facts": {
      "modelId": "google/gemma-3-4b-pt",
      "weights": {
        "paramCount": 4300079472,
        "onDiskBytes": 8600158944,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 4300079472
        },
        "source": "safetensors-index"
      },
      "nLayers": 34,
      "dModel": 2560,
      "nHeads": 0,
      "nKvHeads": 0,
      "headDim": 0,
      "vHeadDim": 0,
      "vocabSize": 262208,
      "intermediateSize": 10240,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 1024,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 0,
      "architecture": "Gemma3ForConditionalGeneration",
      "derivedDims": [
        "max_position_embeddings",
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "config.json states no vocab_size, so it was read from the checkpoint: the embedding matrix is 262,208 rows. This is the term the eager logits are priced from, and pricing it at zero is the direction that hides an OOM.",
        "config.json omits max_position_embeddings, so the model's advertised context is unknown and a max_model_len has to be chosen rather than defaulted.",
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "cc012e0a6d0787b4adcc0fa2c4da74402494554d"
  },
  "google/gemma-4-12b-it": {
    "facts": {
      "modelId": "google/gemma-4-12B-it",
      "weights": {
        "paramCount": 11959730224,
        "onDiskBytes": 23919549408,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 11959730224
        },
        "source": "file-sizes"
      },
      "nLayers": 48,
      "dModel": 3840,
      "nHeads": 16,
      "nKvHeads": 8,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 262144,
      "intermediateSize": 15360,
      "nExperts": 0,
      "layerTypes": [
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention"
      ],
      "slidingWindow": 1024,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Gemma4UnifiedForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "707f0a3b8a3c7ad586ed01e27eafbad8a27dd0f7"
  },
  "google/gemma-4-26b-a4b-it": {
    "facts": {
      "modelId": "google/gemma-4-26B-A4B-it",
      "weights": {
        "paramCount": 25805936206,
        "onDiskBytes": 51611872412,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 25805936206
        },
        "source": "safetensors-index"
      },
      "nLayers": 30,
      "dModel": 2816,
      "nHeads": 16,
      "nKvHeads": 8,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 262144,
      "intermediateSize": 2112,
      "nExperts": 128,
      "layerTypes": [
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention"
      ],
      "slidingWindow": 1024,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Gemma4ForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "4d7ae4984b7db7de8f8457170b3f1a419ee76d52"
  },
  "google/gemma-4-31b": {
    "facts": {
      "modelId": "google/gemma-4-31B",
      "weights": {
        "paramCount": 31273088876,
        "onDiskBytes": 62546177752,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 31273088876
        },
        "source": "safetensors-index"
      },
      "nLayers": 60,
      "dModel": 5376,
      "nHeads": 32,
      "nKvHeads": 16,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 262144,
      "intermediateSize": 21504,
      "nExperts": 0,
      "layerTypes": [
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention"
      ],
      "slidingWindow": 1024,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Gemma4ForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "5bbc2fb1c1b2c611d06e3d9f23c170ba21659d89"
  },
  "google/gemma-4-e2b": {
    "facts": {
      "modelId": "google/gemma-4-E2B",
      "weights": {
        "paramCount": 5123178051,
        "onDiskBytes": 10246621918,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 5123178051
        },
        "source": "file-sizes"
      },
      "nLayers": 35,
      "dModel": 1536,
      "nHeads": 8,
      "nKvHeads": 1,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 262144,
      "intermediateSize": 6144,
      "nExperts": 0,
      "layerTypes": [
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention"
      ],
      "slidingWindow": 512,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 131072,
      "architecture": "Gemma4ForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "d29ff6b45f081a49ee2733a859c9c9c2d95d1a6f"
  },
  "google/gemma-4-e4b": {
    "facts": {
      "modelId": "google/gemma-4-E4B",
      "weights": {
        "paramCount": 7996156490,
        "onDiskBytes": 15992595884,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 7996156490
        },
        "source": "file-sizes"
      },
      "nLayers": 42,
      "dModel": 2560,
      "nHeads": 8,
      "nKvHeads": 2,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 262144,
      "intermediateSize": 10240,
      "nExperts": 0,
      "layerTypes": [
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "sliding_attention",
        "full_attention"
      ],
      "slidingWindow": 512,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 131072,
      "architecture": "Gemma4ForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "411aa17b749aa952df1359d2dcea73917a544d9a"
  },
  "huggingfacetb/smollm3-3b": {
    "facts": {
      "modelId": "HuggingFaceTB/SmolLM3-3B",
      "weights": {
        "paramCount": 3075098624,
        "onDiskBytes": 6150197248,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 3075098624
        },
        "source": "safetensors-index"
      },
      "nLayers": 36,
      "dModel": 2048,
      "nHeads": 16,
      "nKvHeads": 4,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 128256,
      "intermediateSize": 11008,
      "nExperts": 0,
      "layerTypes": [
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 65536,
      "architecture": "SmolLM3ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 128, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "a07cc9a04f16550a088caea529712d1d335b0ac1"
  },
  "ibm-granite/granite-3.0-1b-a400m-base": {
    "facts": {
      "modelId": "ibm-granite/granite-3.0-1b-a400m-base",
      "weights": {
        "paramCount": 1384956928,
        "onDiskBytes": 5539827712,
        "storedDtype": "",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "F32": 1384956928
        },
        "source": "safetensors-index"
      },
      "nLayers": 24,
      "dModel": 1024,
      "nHeads": 16,
      "nKvHeads": 8,
      "headDim": 64,
      "vHeadDim": 64,
      "vocabSize": 49152,
      "intermediateSize": 512,
      "nExperts": 32,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 4096,
      "architecture": "GraniteMoeForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 64, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "d91cbed802d85eb1b32374623331f6ab2b37403a"
  },
  "ibm-granite/granite-3.3-2b-instruct": {
    "facts": {
      "modelId": "ibm-granite/granite-3.3-2b-instruct",
      "weights": {
        "paramCount": 2533539840,
        "onDiskBytes": 5067079680,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 2533539840
        },
        "source": "safetensors-index"
      },
      "nLayers": 40,
      "dModel": 2048,
      "nHeads": 32,
      "nKvHeads": 8,
      "headDim": 64,
      "vHeadDim": 64,
      "vocabSize": 49159,
      "intermediateSize": 8192,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 131072,
      "architecture": "GraniteForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 64, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "707f574c62054322f6b5b04b6d075f0a8f05e0f0"
  },
  "liquidai/lfm2-8b-a1b": {
    "facts": {
      "modelId": "LiquidAI/LFM2-8B-A1B",
      "weights": {
        "paramCount": 8339930560,
        "onDiskBytes": 16679862528,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 8339929856,
          "F32": 704
        },
        "source": "safetensors-index"
      },
      "nLayers": 24,
      "dModel": 2048,
      "nHeads": 32,
      "nKvHeads": 8,
      "headDim": 64,
      "vHeadDim": 64,
      "vocabSize": 65536,
      "intermediateSize": 7168,
      "nExperts": 32,
      "layerTypes": [
        "conv",
        "conv",
        "full_attention",
        "conv",
        "conv",
        "conv",
        "full_attention",
        "conv",
        "conv",
        "conv",
        "full_attention",
        "conv",
        "conv",
        "conv",
        "full_attention",
        "conv",
        "conv",
        "conv",
        "full_attention",
        "conv",
        "conv",
        "full_attention",
        "conv",
        "conv"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 128000,
      "architecture": "Lfm2MoeForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 64, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "c1c44ff9fc00db3ebf4516970563f5f383d23670"
  },
  "liquidai/lfm2.5-230m": {
    "facts": {
      "modelId": "LiquidAI/LFM2.5-230M",
      "weights": {
        "paramCount": 229693184,
        "onDiskBytes": 459401112,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 229693184
        },
        "source": "file-sizes"
      },
      "nLayers": 14,
      "dModel": 1024,
      "nHeads": 16,
      "nKvHeads": 8,
      "headDim": 64,
      "vHeadDim": 64,
      "vocabSize": 65536,
      "intermediateSize": 2560,
      "nExperts": 0,
      "layerTypes": [
        "conv",
        "conv",
        "full_attention",
        "conv",
        "full_attention",
        "conv",
        "full_attention",
        "conv",
        "full_attention",
        "conv",
        "full_attention",
        "conv",
        "full_attention",
        "conv"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 128000,
      "architecture": "Lfm2ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 64, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "40cb2ad3b3044d5a41eee083a6103c8b523afa45"
  },
  "meta-llama/llama-3.1-8b": {
    "facts": {
      "modelId": "meta-llama/Llama-3.1-8B",
      "weights": {
        "paramCount": 8030261248,
        "onDiskBytes": 16060522496,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 8030261248
        },
        "source": "safetensors-index"
      },
      "nLayers": 32,
      "dModel": 4096,
      "nHeads": 32,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 128256,
      "intermediateSize": 14336,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 131072,
      "architecture": "LlamaForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 128, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "d04e592bb4f6aa9cfee91e2e20afa771667e1d4b"
  },
  "meta-llama/llama-3.1-8b-instruct": {
    "facts": {
      "modelId": "meta-llama/Llama-3.1-8B-Instruct",
      "weights": {
        "paramCount": 8030261248,
        "onDiskBytes": 16060522496,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 8030261248
        },
        "source": "safetensors-index"
      },
      "nLayers": 32,
      "dModel": 4096,
      "nHeads": 32,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 128256,
      "intermediateSize": 14336,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 131072,
      "architecture": "LlamaForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 128, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "0e9e39f249a16976918f6564b8830bc894c89659"
  },
  "meta-llama/llama-3.3-70b-instruct": {
    "facts": {
      "modelId": "meta-llama/Llama-3.3-70B-Instruct",
      "weights": {
        "paramCount": 70553706496,
        "onDiskBytes": 141107412992,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 70553706496
        },
        "source": "safetensors-index"
      },
      "nLayers": 80,
      "dModel": 8192,
      "nHeads": 64,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 128256,
      "intermediateSize": 28672,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 131072,
      "architecture": "LlamaForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": "manual",
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "6f6073b423013f6a7d4d9f39144961bfbfbc386b"
  },
  "microsoft/phi-2": {
    "facts": {
      "modelId": "microsoft/phi-2",
      "weights": {
        "paramCount": 2779683840,
        "onDiskBytes": 5559367680,
        "storedDtype": "float16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "F16": 2779683840
        },
        "source": "safetensors-index"
      },
      "nLayers": 32,
      "dModel": 2560,
      "nHeads": 32,
      "nKvHeads": 32,
      "headDim": 80,
      "vHeadDim": 80,
      "vocabSize": 51200,
      "intermediateSize": 10240,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 2048,
      "architecture": "PhiForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 80, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "810d367871c1d460086d9f82db8696f2e0a0fcd0"
  },
  "microsoft/phi-3-mini-4k-instruct": {
    "facts": {
      "modelId": "microsoft/Phi-3-mini-4k-instruct",
      "weights": {
        "paramCount": 3821079552,
        "onDiskBytes": 7642159104,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 3821079552
        },
        "source": "safetensors-index"
      },
      "nLayers": 32,
      "dModel": 3072,
      "nHeads": 32,
      "nKvHeads": 32,
      "headDim": 96,
      "vHeadDim": 96,
      "vocabSize": 32064,
      "intermediateSize": 8192,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 2047,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 4096,
      "architecture": "Phi3ForCausalLM",
      "derivedDims": [
        "head_dim",
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim, so it was derived as hidden_size / num_attention_heads. Some families set a different value in their model class (gemma-3-12b's is 256 where the division gives 240), and a derived value that is too small UNDER-states the KV cache.",
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "f39ac1d28e925b323eae81227eaba4464caced4e"
  },
  "microsoft/phi-mini-moe-instruct": {
    "facts": {
      "modelId": "microsoft/Phi-mini-MoE-instruct",
      "weights": {
        "paramCount": 7647632704,
        "onDiskBytes": 15295265408,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 7647632704
        },
        "source": "safetensors-index"
      },
      "nLayers": 32,
      "dModel": 4096,
      "nHeads": 32,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 32064,
      "intermediateSize": 960,
      "nExperts": 16,
      "layerTypes": null,
      "slidingWindow": 2047,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 4096,
      "architecture": "PhiMoEForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "f620b32c0d3e8f7e76f57ccdaa88e0df8bc8bfcd"
  },
  "mistralai/mistral-7b-v0.1": {
    "facts": {
      "modelId": "mistralai/Mistral-7B-v0.1",
      "weights": {
        "paramCount": 7241732096,
        "onDiskBytes": 14483464192,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 7241732096
        },
        "source": "safetensors-index"
      },
      "nLayers": 32,
      "dModel": 4096,
      "nHeads": 32,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 32000,
      "intermediateSize": 14336,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 4096,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 32768,
      "architecture": "MistralForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 128, so the KV figures are exact rather than derived from hidden_size / heads.",
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "27d67f1b5f57dc0953326b2601d68371d40ea8da"
  },
  "nvidia/llama-3.3-70b-instruct-fp4": {
    "facts": {
      "modelId": "nvidia/Llama-3.3-70B-Instruct-FP4",
      "weights": {
        "paramCount": 74831896736,
        "onDiskBytes": 42709045632,
        "storedDtype": "bfloat16",
        "quantMethod": "nvfp4",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 2102665376,
          "F8_E4M3": 4278190080,
          "U8": 34225520640
        },
        "source": "safetensors-index"
      },
      "nLayers": 80,
      "dModel": 8192,
      "nHeads": 64,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 128256,
      "intermediateSize": 28672,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 131072,
      "architecture": "LlamaForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "fp8",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "f792b707002f2c613e0729c6b37bbcedc4efa94e"
  },
  "nvidia/nvidia-nemotron-3-nano-4b-bf16": {
    "facts": {
      "modelId": "nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16",
      "weights": {
        "paramCount": 3973556832,
        "onDiskBytes": 7947142640,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 3973556832
        },
        "source": "file-sizes"
      },
      "nLayers": 42,
      "dModel": 3136,
      "nHeads": 40,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 131072,
      "intermediateSize": 12544,
      "nExperts": 0,
      "layerTypes": [
        "linear_attention",
        "mlp",
        "linear_attention",
        "mlp",
        "linear_attention",
        "mlp",
        "linear_attention",
        "linear_attention",
        "mlp",
        "linear_attention",
        "mlp",
        "linear_attention",
        "full_attention",
        "mlp",
        "linear_attention",
        "mlp",
        "linear_attention",
        "full_attention",
        "mlp",
        "linear_attention",
        "mlp",
        "linear_attention",
        "mlp",
        "linear_attention",
        "full_attention",
        "mlp",
        "linear_attention",
        "mlp",
        "linear_attention",
        "mlp",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "mlp",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "mlp",
        "linear_attention",
        "mlp",
        "linear_attention",
        "mlp"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "NemotronHForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "dfaf35de3e30f1867dd8dbc38a7fc9fb52d3914f"
  },
  "openai-community/gpt2": {
    "facts": {
      "modelId": "openai-community/gpt2",
      "weights": {
        "paramCount": 137022720,
        "onDiskBytes": 548105171,
        "storedDtype": "",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "F32": 137022720
        },
        "source": "file-sizes"
      },
      "nLayers": 12,
      "dModel": 768,
      "nHeads": 12,
      "nKvHeads": 12,
      "headDim": 64,
      "vHeadDim": 64,
      "vocabSize": 50257,
      "intermediateSize": 3072,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 1024,
      "architecture": "GPT2LMHeadModel",
      "derivedDims": [
        "head_dim"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim, so it was derived as hidden_size / num_attention_heads. Some families set a different value in their model class (gemma-3-12b's is 256 where the division gives 240), and a derived value that is too small UNDER-states the KV cache."
      ]
    },
    "sha": "607a30d783dfa663caf39e06633721c8d4cfcd7e"
  },
  "openai/gpt-oss-20b": {
    "facts": {
      "modelId": "openai/gpt-oss-20b",
      "weights": {
        "paramCount": 22109150784,
        "onDiskBytes": 13761264768,
        "storedDtype": "",
        "quantMethod": "mxfp4",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 1804459584,
          "U8": 10152345600
        },
        "source": "safetensors-index"
      },
      "nLayers": 24,
      "dModel": 2880,
      "nHeads": 64,
      "nKvHeads": 8,
      "headDim": 64,
      "vHeadDim": 64,
      "vocabSize": 201088,
      "intermediateSize": 2880,
      "nExperts": 32,
      "layerTypes": [
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "full_attention",
        "sliding_attention",
        "full_attention"
      ],
      "slidingWindow": 128,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 131072,
      "architecture": "GptOssForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "6cee5e81ee83917806bbde320786a8fb61efebee"
  },
  "qwen/qwen2.5-1.5b-instruct": {
    "facts": {
      "modelId": "Qwen/Qwen2.5-1.5B-Instruct",
      "weights": {
        "paramCount": 1543714304,
        "onDiskBytes": 3087467144,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 1543714304
        },
        "source": "file-sizes"
      },
      "nLayers": 28,
      "dModel": 1536,
      "nHeads": 12,
      "nKvHeads": 2,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 151936,
      "intermediateSize": 8960,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 32768,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 32768,
      "architecture": "Qwen2ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 128, so the KV figures are exact rather than derived from hidden_size / heads.",
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "989aa7980e4cf806f80c7fef2b1adb7bc71aa306"
  },
  "qwen/qwen2.5-7b-instruct": {
    "facts": {
      "modelId": "Qwen/Qwen2.5-7B-Instruct",
      "weights": {
        "paramCount": 7615616512,
        "onDiskBytes": 15231233024,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 7615616512
        },
        "source": "safetensors-index"
      },
      "nLayers": 28,
      "dModel": 3584,
      "nHeads": 28,
      "nKvHeads": 4,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 152064,
      "intermediateSize": 18944,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": 131072,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 32768,
      "architecture": "Qwen2ForCausalLM",
      "derivedDims": [
        "layer_types"
      ],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 128, so the KV figures are exact rather than derived from hidden_size / heads.",
        "this model declares a sliding window but no per-layer table, so every layer is priced as if it caches the full context. That over-states the KV cache, often by a lot: a 5:1 sliding trunk really caches the window on five layers in six."
      ]
    },
    "sha": "a09a35458c702b33eeacc393d103063234e8bc28"
  },
  "qwen/qwen3-1.7b": {
    "facts": {
      "modelId": "Qwen/Qwen3-1.7B",
      "weights": {
        "paramCount": 2031739904,
        "onDiskBytes": 4063479808,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 2031739904
        },
        "source": "safetensors-index"
      },
      "nLayers": 28,
      "dModel": 2048,
      "nHeads": 16,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 151936,
      "intermediateSize": 6144,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 40960,
      "architecture": "Qwen3ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "70d244cc86ccca08cf5af4e1e306ecf908b1ad5e"
  },
  "qwen/qwen3-14b": {
    "facts": {
      "modelId": "Qwen/Qwen3-14B",
      "weights": {
        "paramCount": 14768307200,
        "onDiskBytes": 29536614400,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 14768307200
        },
        "source": "safetensors-index"
      },
      "nLayers": 40,
      "dModel": 5120,
      "nHeads": 40,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 151936,
      "intermediateSize": 17408,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 40960,
      "architecture": "Qwen3ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "40c069824f4251a91eefaf281ebe4c544efd3e18"
  },
  "qwen/qwen3-30b-a3b": {
    "facts": {
      "modelId": "Qwen/Qwen3-30B-A3B",
      "weights": {
        "paramCount": 30532122624,
        "onDiskBytes": 61064245248,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 30532122624
        },
        "source": "safetensors-index"
      },
      "nLayers": 48,
      "dModel": 2048,
      "nHeads": 32,
      "nKvHeads": 4,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 151936,
      "intermediateSize": 6144,
      "nExperts": 128,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 40960,
      "architecture": "Qwen3MoeForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "ad44e777bcd18fa416d9da3bd8f70d33ebb85d39"
  },
  "qwen/qwen3-32b": {
    "facts": {
      "modelId": "Qwen/Qwen3-32B",
      "weights": {
        "paramCount": 32762123264,
        "onDiskBytes": 65524246528,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 32762123264
        },
        "source": "safetensors-index"
      },
      "nLayers": 64,
      "dModel": 5120,
      "nHeads": 64,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 151936,
      "intermediateSize": 25600,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 40960,
      "architecture": "Qwen3ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "9216db5781bf21249d130ec9da846c4624c16137"
  },
  "qwen/qwen3-4b": {
    "facts": {
      "modelId": "Qwen/Qwen3-4B",
      "weights": {
        "paramCount": 4022468096,
        "onDiskBytes": 8044936192,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 4022468096
        },
        "source": "safetensors-index"
      },
      "nLayers": 36,
      "dModel": 2560,
      "nHeads": 32,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 151936,
      "intermediateSize": 9728,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 40960,
      "architecture": "Qwen3ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "1cfa9a7208912126459214e8b04321603b3df60c"
  },
  "qwen/qwen3-8b": {
    "facts": {
      "modelId": "Qwen/Qwen3-8B",
      "weights": {
        "paramCount": 8190735360,
        "onDiskBytes": 16381470720,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 8190735360
        },
        "source": "safetensors-index"
      },
      "nLayers": 36,
      "dModel": 4096,
      "nHeads": 32,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 151936,
      "intermediateSize": 12288,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 40960,
      "architecture": "Qwen3ForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "b968826d9c46dd6066d109eabc6255188de91218"
  },
  "qwen/qwen3-next-80b-a3b-instruct": {
    "facts": {
      "modelId": "Qwen/Qwen3-Next-80B-A3B-Instruct",
      "weights": {
        "paramCount": 81324862720,
        "onDiskBytes": 162649725440,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 81324862720
        },
        "source": "safetensors-index"
      },
      "nLayers": 48,
      "dModel": 2048,
      "nHeads": 16,
      "nKvHeads": 2,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 151936,
      "intermediateSize": 5120,
      "nExperts": 512,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Qwen3NextForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "9c7f2fbe84465e40164a94cc16cd30b6999b0cc7"
  },
  "qwen/qwen3.5-0.8b": {
    "facts": {
      "modelId": "Qwen/Qwen3.5-0.8B",
      "weights": {
        "paramCount": 873438784,
        "onDiskBytes": 1746882752,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 873436192,
          "F32": 2592
        },
        "source": "safetensors-index"
      },
      "nLayers": 24,
      "dModel": 1024,
      "nHeads": 8,
      "nKvHeads": 2,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 248320,
      "intermediateSize": 3584,
      "nExperts": 0,
      "layerTypes": [
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Qwen3_5ForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "2fc06364715b967f1860aea9cf38778875588b17"
  },
  "qwen/qwen3.5-27b": {
    "facts": {
      "modelId": "Qwen/Qwen3.5-27B",
      "weights": {
        "paramCount": 27781427952,
        "onDiskBytes": 55562872800,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 27781419504,
          "F32": 8448
        },
        "source": "safetensors-index"
      },
      "nLayers": 64,
      "dModel": 5120,
      "nHeads": 24,
      "nKvHeads": 4,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 248320,
      "intermediateSize": 17408,
      "nExperts": 0,
      "layerTypes": [
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Qwen3_5ForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "fc05daec18b0a78c049392ed2e771dde82bdf654"
  },
  "qwen/qwen3.5-2b-base": {
    "facts": {
      "modelId": "Qwen/Qwen3.5-2B-Base",
      "weights": {
        "paramCount": 2274069824,
        "onDiskBytes": 4548144832,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 2274067232,
          "F32": 2592
        },
        "source": "safetensors-index"
      },
      "nLayers": 24,
      "dModel": 2048,
      "nHeads": 8,
      "nKvHeads": 2,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 248320,
      "intermediateSize": 6144,
      "nExperts": 0,
      "layerTypes": [
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Qwen3_5ForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "b1485b2fa6dfa1287294f269f5fb618e03d52d7c"
  },
  "qwen/qwen3.5-4b": {
    "facts": {
      "modelId": "Qwen/Qwen3.5-4B",
      "weights": {
        "paramCount": 4659865088,
        "onDiskBytes": 9319737856,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 4659861248,
          "F32": 3840
        },
        "source": "safetensors-index"
      },
      "nLayers": 32,
      "dModel": 2560,
      "nHeads": 16,
      "nKvHeads": 4,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 248320,
      "intermediateSize": 9216,
      "nExperts": 0,
      "layerTypes": [
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Qwen3_5ForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a"
  },
  "qwen/qwen3.5-9b-base": {
    "facts": {
      "modelId": "Qwen/Qwen3.5-9B-Base",
      "weights": {
        "paramCount": 9653104368,
        "onDiskBytes": 19306216416,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 9653100528,
          "F32": 3840
        },
        "source": "safetensors-index"
      },
      "nLayers": 32,
      "dModel": 4096,
      "nHeads": 16,
      "nKvHeads": 4,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 248320,
      "intermediateSize": 12288,
      "nExperts": 0,
      "layerTypes": [
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Qwen3_5ForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "68c46c4b3498877f3ef123c856ecfde50c39f404"
  },
  "qwen/qwen3.6-27b": {
    "facts": {
      "modelId": "Qwen/Qwen3.6-27B",
      "weights": {
        "paramCount": 27781427952,
        "onDiskBytes": 55562855904,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 27781427952
        },
        "source": "safetensors-index"
      },
      "nLayers": 64,
      "dModel": 5120,
      "nHeads": 24,
      "nKvHeads": 4,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 248320,
      "intermediateSize": 17408,
      "nExperts": 0,
      "layerTypes": [
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Qwen3_5ForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "6a9e13bd6fc8f0983b9b99948120bc37f49c13e9"
  },
  "qwen/qwen3.6-35b-a3b": {
    "facts": {
      "modelId": "Qwen/Qwen3.6-35B-A3B",
      "weights": {
        "paramCount": 35951822704,
        "onDiskBytes": 71903645408,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 35951822704
        },
        "source": "safetensors-index"
      },
      "nLayers": 40,
      "dModel": 2048,
      "nHeads": 16,
      "nKvHeads": 2,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 248320,
      "intermediateSize": 512,
      "nExperts": 256,
      "layerTypes": [
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Qwen3_5MoeForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "995ad96eacd98c81ed38be0c5b274b04031597b0"
  },
  "qwen/qwen3.8-27b": {
    "facts": {
      "modelId": "Qwen/Qwen3.8-27B",
      "weights": {
        "paramCount": 27781427952,
        "onDiskBytes": 55562855904,
        "storedDtype": "bfloat16",
        "quantMethod": "",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 27781427952
        },
        "source": "safetensors-index"
      },
      "nLayers": 64,
      "dModel": 5120,
      "nHeads": 24,
      "nKvHeads": 4,
      "headDim": 256,
      "vHeadDim": 256,
      "vocabSize": 248320,
      "intermediateSize": 17408,
      "nExperts": 0,
      "layerTypes": [
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention",
        "linear_attention",
        "linear_attention",
        "linear_attention",
        "full_attention"
      ],
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 262144,
      "architecture": "Qwen3_5ForConditionalGeneration",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": []
    },
    "sha": "1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0"
  },
  "redhatai/meta-llama-3.1-8b-instruct-fp8": {
    "facts": {
      "modelId": "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8",
      "weights": {
        "paramCount": 8030261248,
        "onDiskBytes": 9081201536,
        "storedDtype": "bfloat16",
        "quantMethod": "compressed-tensors",
        "expertDtype": "",
        "elementsByDtype": {
          "BF16": 1050939392,
          "F8_E4M3": 6979321856
        },
        "source": "safetensors-index"
      },
      "nLayers": 32,
      "dModel": 4096,
      "nHeads": 32,
      "nKvHeads": 8,
      "headDim": 128,
      "vHeadDim": 128,
      "vocabSize": 128256,
      "intermediateSize": 14336,
      "nExperts": 0,
      "layerTypes": null,
      "slidingWindow": null,
      "nResidualStreams": 1,
      "maxPositionEmbeddings": 131072,
      "architecture": "LlamaForCausalLM",
      "derivedDims": [],
      "kvQuantAlgo": "",
      "gated": false,
      "trunkDimsKnown": true,
      "notes": [
        "config.json omits head_dim; the key projection in the checkpoint gives 128, so the KV figures are exact rather than derived from hidden_size / heads."
      ]
    },
    "sha": "870a1177ed082c0ba5dbefd62573ab8f91803f6a"
  },
};
