"""Generate `docs/MODELS_STATUS.md` and the README's support summary from what the suite already knows.

The question this answers is the one a user asks first and no single test answers: *will it load my
model, and can I trust what it gives me?* Both halves matter, and they are established by different
evidence, so the doc sorts every architecture by **what has actually been shown about it**:

- **verified** -- captured on real weights and agreed with independent engines (TransformerLens,
  nnsight, vLLM, SGLang) point by point. From `comparison/results/`.
- **resolves** -- every canonical point resolves against the real module tree, or is refused with a
  reason, on a model built from the family's config defaults (`family_coverage.audit()`), *and* the
  three arithmetic invariants hold on a tiny random model of the family (`tests/test_invariants.py`).
  Together those say the engine found the right modules; what is unverified is agreement with another
  implementation on real weights.
- **unaudited** -- nothing was probed, because transformers has no class for the family (vLLM
  implements it natively and the checkpoint ships its own modeling code) or because its config
  defaults do not survive its own `__init__`. Not a negative verdict: most of these would load.
- **broken** -- a module tree the engine's `(point, layer)` addressing cannot express, with the
  structural reason. Four families, and each entry says what it would take.

Nothing here is hand-maintained. The tiers are computed, the reasons come from the tables in
`family_coverage.py` that `test_family_coverage.py` pins, and `test_models_status.py` fails if the
committed doc drifts from any of its sources. Which is the point: a support matrix nobody can trust to
be current is worse than none, because it will be read as a promise.

Regenerate (needs network -- see `--allow-offline`)::

    PYTHONPATH=. .venv-cmp/bin/python tests/models_status.py

Refresh the checkpoint-to-family map after adding a model to the sweep (needs network)::

    PYTHONPATH=. .venv-cmp/bin/python tests/models_status.py --refresh-architectures
"""

from __future__ import annotations

import argparse
import collections
import json
import os
import pathlib
import sys

import family_coverage as fc
import invariants

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "MODELS_STATUS.md"
README = ROOT / "README.md"
RESULTS = ROOT / "comparison" / "results"
SWEEP = ROOT / "comparison" / "sweep_models.json"
ARCHITECTURES = ROOT / "comparison" / "sweep_architectures.json"

START = "<!-- MODEL-SUPPORT:START -->"
END = "<!-- MODEL-SUPPORT:END -->"

GENERATED = "<!-- Generated by tests/models_status.py -- do not edit by hand. -->"

VERIFIED, RESOLVES, UNAUDITED, BROKEN = "verified", "resolves", "unaudited", "broken"

# One line each, used in both documents so the two cannot describe a tier differently.
TIER_SUMMARY: dict[str, str] = {
    VERIFIED: "captured on real weights and checked point-by-point against other engines",
    RESOLVES: "every point resolves and the arithmetic invariants hold; no independent engine has reproduced it",
    UNAUDITED: "not probed: transformers has no class for the family, or its own config defaults do not build",
    BROKEN: "a module tree the `(point, layer)` addressing cannot express, with the reason",
}

# The audit statuses that mean "we learned nothing", as opposed to "we learned it does not work".
_UNAUDITED_STATUSES = frozenset({"no_transformers_class", "not_buildable", "needs_download"})


def sweep_architectures() -> dict[str, str]:
    """Committed map from the sweep's HF repo ids to the architecture each checkpoint declares.

    Committed rather than read from the hub, so the doc generates and its drift test runs offline. It is
    also not derivable from the results on disk: a cell records the capture, not the checkpoint's class.
    """
    return {k: v for k, v in json.loads(ARCHITECTURES.read_text()).items() if not k.startswith("_")}


def verified_checkpoints() -> dict[str, dict[str, str]]:
    """``{hf_id: {engine: verdict}}`` for every cell the comparison sweep has committed."""
    rows: dict[str, dict[str, str]] = collections.defaultdict(dict)
    for path in sorted(RESULTS.glob("*/*/*.json")):
        hf_id = f"{path.parent.parent.name}/{path.parent.name}"
        rows[hf_id][path.stem] = str(json.loads(path.read_text()).get("verdict") or "")
    return dict(rows)


#: Engines written by someone else. Agreement from these is the whole evidentiary value of the sweep:
#: interp-engine's own eager and vLLM backends share this repository's reading of an architecture, so
#: the two of them matching says only that the reading is applied consistently.
INDEPENDENT_ENGINES = frozenset({"tlens_v2", "tlens_v3", "nnsight", "sglang"})


def verified_families(checkpoints: dict[str, dict[str, str]], architectures: dict[str, str]) -> dict[str, dict]:
    """Group the sweep by architecture, keeping what each family's evidence actually is.

    ``agreeing`` is the set of engines that agreed on *every* checkpoint of the family, which is the
    only honest way to summarize a family whose members were compared against different engine sets
    (TransformerLens v2 cannot load half of them, SGLang serves bf16 only).
    """
    families: dict[str, dict] = {}
    for hf_id, cells in sorted(checkpoints.items()):
        arch = architectures.get(hf_id)
        if arch is None:
            continue
        agreed = {engine for engine, verdict in cells.items() if verdict == "✅"}
        entry = families.setdefault(arch, {"checkpoints": [], "agreeing": None})
        entry["checkpoints"].append(hf_id)
        entry["agreeing"] = agreed if entry["agreeing"] is None else entry["agreeing"] & agreed
    return families


def corroborated(families: dict[str, dict]) -> dict[str, dict]:
    """The families whose sweep actually produced evidence, which is not all the families it ran on.

    A cell exists whenever the sweep *attempted* a checkpoint, and the attempt can end with every
    independent engine erroring out -- Nemotron-H and LFM2-MoE captured against eager and nothing
    else. Grouping by "has results" would file those under the strongest claim in the repo on the
    strength of interp-engine agreeing with itself, which is the one thing the sweep is not for.
    """
    return {arch: entry for arch, entry in families.items() if entry["agreeing"] & INDEPENDENT_ENGINES}


def uncorroborated(families: dict[str, dict]) -> dict[str, dict]:
    """The complement: swept, and no independently written engine reproduced it. Reported rather than
    dropped, since "tried and got nothing" is a different state from "not tried"."""
    return {arch: entry for arch, entry in families.items() if not entry["agreeing"] & INDEPENDENT_ENGINES}


def tier_of(arch: str, report: fc.Coverage | None, verified: set[str]) -> str:
    """Which tier one architecture is in. Order matters: evidence outranks the absence of it."""
    if arch in fc.KNOWN_GAPS:
        return BROKEN
    if arch in verified:
        return VERIFIED
    if report is None:
        return UNAUDITED
    if report.status == "not_loadable":
        return BROKEN
    if report.status in _UNAUDITED_STATUSES:
        return UNAUDITED
    return RESOLVES


def tiers(reports: dict[str, fc.Coverage], verified: set[str]) -> dict[str, list[str]]:
    """Every architecture we make any claim about, bucketed. Sorted, so a diff reads as a change."""
    out: dict[str, list[str]] = {tier: [] for tier in TIER_SUMMARY}
    for arch in sorted(set(reports) | verified):
        out[tier_of(arch, reports.get(arch), verified)].append(arch)
    return out


# --- rendering ---------------------------------------------------------------


def _table(headers: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(lines)


def _points_absent(report: fc.Coverage) -> str:
    absent = [p for p in fc.CONDITIONAL_POINTS if report.points.get(p) != "ok"]
    absent += [p for p in fc.CORE_POINTS if report.points.get(p) != "ok"]
    return ", ".join(f"`{p}`" for p in absent) if absent else "--"


def _invariants(arch: str) -> str:
    """What the invariant sweep says about one family, from the tables its test enforces.

    Read from the tables rather than by running the sweep, because the sweep *is* a test: an entry here
    is a claim `tests/test_invariants.py` fails on if it stops being true.
    """
    if arch in invariants.NOT_MINIATURIZABLE:
        return "not checked: " + invariants.NOT_MINIATURIZABLE[arch].split(",")[0]
    excepted = [name for (family, name) in invariants.EXCEPTIONS if family == arch]
    if excepted:
        return "all but " + ", ".join(f"`{name}`" for name in sorted(excepted))
    return "hold"


def render_summary(buckets: dict[str, list[str]], families: dict[str, dict], vllm_version: str) -> str:
    """The README block: four counts and what each one means. Deliberately not the family lists."""
    checkpoints = sum(len(entry["checkpoints"]) for entry in families.values())
    rows = [
        [f"**{tier}**", str(len(buckets[tier])), TIER_SUMMARY[tier]] for tier in (VERIFIED, RESOLVES, UNAUDITED, BROKEN)
    ]
    return "\n".join(
        [
            f"Support is tracked per **architecture**, against vLLM {vllm_version}'s model registry -- what this",
            "engine has to cover is what a user can serve. Both columns below come from tests, not from a",
            "maintained list:",
            "",
            _table(["", "architectures", "what has been shown"], rows),
            "",
            f"Verified today, on {checkpoints} checkpoints between them:",
            "",
            ", ".join(f"`{arch}`" for arch in buckets[VERIFIED]) + ".",
            "",
            "Unverified is the absence of a *cross-engine* run, not a prediction of failure: an architecture in the",
            "second tier resolves every hook point against its real module tree and satisfies three arithmetic",
            "invariants on a tiny random model of the family -- `attn_probs @ value == z`, `resid_pre + attn_out_post",
            "+ mlp_out_post == resid_post`, and `down_proj(mlp_act) == mlp_out`. Where a point genuinely does not",
            "exist -- a Mamba block's attention, a latent-attention",
            "model's `value`, the residual between the sublayers of a parallel block -- it is refused with an",
            "explanation rather than returned as a plausible tensor.",
            "[docs/MODELS_STATUS.md](docs/MODELS_STATUS.md) has every architecture by name, with the reason and,",
            "for the unverified, what would promote it.",
        ]
    )


def render_doc(
    reports: dict[str, fc.Coverage],
    families: dict[str, dict],
    unconfirmed: dict[str, dict],
    vllm_version: str,
) -> str:
    verified = set(families)
    buckets = tiers(reports, verified)
    out: list[str] = [
        GENERATED,
        "",
        "# Model support status",
        "",
        "Every architecture below is one vLLM can serve, plus the multimodal wrappers the comparison sweep",
        f"covers. The list is a snapshot of vLLM {vllm_version}'s registry",
        "(`tests/vllm_supported_archs.json`): a serving runtime's registry is the only definition of \"models",
        'people run" that stays current without anyone curating it. Families vLLM serves through its',
        "transformers backend rather than a native implementation count too -- vLLM serves them either way.",
        "",
        "The tiers are **what has been shown**, not a forecast:",
        "",
    ]
    out += [f"- **{tier}** -- {TIER_SUMMARY[tier]} ({len(buckets[tier])} architectures)" for tier in TIER_SUMMARY]
    out += [
        "",
        "The distinction that matters most is between *resolves* and *verified*. Resolution walks the module",
        "tree and matches attribute names, so it catches the failure this engine is most prone to -- a family",
        "that spells `self_attention` where its cousins spell `self_attn` loses that point entirely, on every",
        "checkpoint, silently. What it cannot catch is a point that resolves to the *wrong* module: a fused",
        "`qkv` split by the wrong layout yields a correctly shaped `value` holding a mix of queries and keys,",
        "and only a numeric check against another implementation notices. That is what the sweep is for, and",
        "it is why the top tier is small and per-checkpoint.",
        "",
        "## Verified numerically",
        "",
        "Captured on real weights and compared point-by-point against the engines named, at the tolerances in",
        "`comparison/spec.py`. `agreeing engines` lists only engines that agreed on **every** checkpoint of the",
        "family. The full matrix, with per-point cosines and the command to reproduce any cell, is the table in",
        "[README.md](../README.md) and the JSON under `comparison/results/`.",
        "",
    ]
    rows = []
    for arch in buckets[VERIFIED]:
        entry = families[arch]
        checkpoints = "<br>".join(f"`{c}`" for c in entry["checkpoints"])
        rows.append([f"`{arch}`", checkpoints, ", ".join(sorted(entry["agreeing"]))])
    out += [_table(["architecture", "checkpoints", "agreeing engines"], rows), ""]
    out += [
        "A verified architecture is evidence about its **family**, not only about the checkpoints listed: the",
        "module tree and the names are shared, so a same-family checkpoint at another size differs in dims and",
        "in nothing that resolution depends on. Different *generations* are a different matter (Gemma-2 and",
        "Gemma-3 disagree about where their norms are), which is why each generation appears on its own row.",
        "",
    ]
    if unconfirmed:
        out += [
            "## Swept, and nothing independent came back",
            "",
            "Not a tier -- each family below keeps whichever tier the audit gives it -- but the distinction the",
            "tiers cannot draw: these were *tried*. Each has committed results, so a cell exists, but no",
            "independently written engine finished. The comparisons errored, crashed or were skipped as",
            "unsupported, leaving interp-engine's own two backends as the only ones that captured, and those",
            "two share this repository's reading of the architecture. Their agreement is not evidence, so these",
            "are not verified; the failing runs are the thing to fix, and they are easy to lose sight of once",
            "the family is filed under a weaker claim.",
            "",
            _table(
                ["architecture", "checkpoints"],
                [
                    [f"`{arch}`", "<br>".join(f"`{c}`" for c in entry["checkpoints"])]
                    for arch, entry in sorted(unconfirmed.items())
                ],
            ),
            "",
        ]
    out += [
        "## Resolves, unverified numerically",
        "",
        "Every canonical point resolves against the real module tree, or is refused with an explanation, and",
        "the three invariants below hold on a tiny randomly initialized model of the family. Resolution is",
        "checked on the `meta` device from each family's config defaults; the invariants run a real forward on",
        "a shrunk config. No weights are downloaded for either. `absent points` are the ones refused -- read",
        "the legend below before reading them as gaps.",
        "",
    ]
    rows = [[f"`{arch}`", _points_absent(reports[arch]), _invariants(arch)] for arch in buckets[RESOLVES]]
    out += [_table(["architecture", "absent points", "invariants"], rows), ""]
    out += [
        "Which points are absent says which shape the MLP has, and the three cases are worth telling apart:",
        "",
        "- **`mlp_pre_linear` alone** -- a plain (ungated) MLP: `up_proj` then activation then `down_proj`, with",
        "  no second branch to multiply, so the point names nothing. GPT-2, OPT, BLOOM, MPT, GPT-J, phi-2.",
        "- **`mlp_pre` and `mlp_pre_linear`** -- a gated MLP whose gate and up projections are *one fused",
        "  matrix* (`gate_up_proj`), so neither branch is a module output. `mlp_act` survives, since it is the",
        "  down projection's input either way -- and that is the neuron basis SAEs are trained on.",
        "- **all three** -- a sparse mixture of experts, where the projections live on the experts rather than",
        "  at the block boundary. Those families report `router_logits` / `expert_weights` / `expert_indices`",
        "  instead, which is the information `mlp_out` cannot recover.",
        "",
        "And the other two:",
        "",
        "- **`value`** -- multi-head latent attention (DeepSeek-V2/V3, MiniCPM3, GLM-MoE) keeps a compressed kv",
        "  latent and expands it inside the forward, so no module's output is the value. `z` still exists; it is",
        "  direct feature attribution that is unavailable.",
        "- **`resid_mid`** -- a parallel block (GPT-NeoX, Falcon, GPT-J, phi-2, Cohere) has no residual *between*",
        "  its sublayers, because nothing sequences them. A single-sublayer block (Nemotron-H) has none either.",
        "",
        "A family missing the attention or MLP points entirely is a state-space or all-linear-attention trunk,",
        "which the next table records explicitly.",
        "",
        "### Points an architecture does not have",
        "",
        "Recorded facts rather than gaps, from `family_coverage.ARCHITECTURAL_ABSENCES`. Everything else about",
        "these families works, including the residual stream, which is where interpretability on them happens.",
        "",
        _table(
            ["architecture", "absent", "why"],
            [
                [f"`{arch}`", ", ".join(f"`{p}`" for p in sorted(points)), why]
                for arch, (points, why) in sorted(fc.ARCHITECTURAL_ABSENCES.items())
            ],
        ),
        "",
        "### Attention with no separable value (no DFA)",
        "",
        _table(
            ["architecture", "why"],
            [[f"`{arch}`", why] for arch, why in sorted(fc.KNOWN_NO_VALUE.items())],
        ),
        "",
        "### The three invariants",
        "",
        "Each fails loudly on the misbinding resolution cannot catch, and none needs a second framework, so all",
        "three run over every family in this tier (`tests/test_invariants.py`, on tiny random models):",
        "",
        "1. **DFA** -- `attn_probs @ value == z` per head. Catches a wrong fused-qkv layout, a mis-split head, a",
        "   `value` that is really a key, and a value the family rescales after projecting it.",
        "2. **residual decomposition** -- `resid_pre + attn_out_post + mlp_out_post == resid_post`. Catches a",
        "   post-sublayer norm read from the wrong side of an add, a sublayer whose output already includes the",
        "   residual, and a residual multiplier left unapplied.",
        "3. **neuron basis** -- `down_proj(mlp_act) == mlp_out`. Catches a neuron basis resolved to the wrong",
        "   projection of a gated MLP.",
        "",
        "Random weights are enough because these are identities the *architecture* satisfies at any weights, and",
        "a family whose quantity does not exist is expected to refuse with a reason -- a refusal passes, a wrong",
        "number does not. What random weights cannot reach is anything a trained config turns on: Granite's",
        "`residual_multiplier` is 1.0 by default and 0.22 on the released checkpoints, so that case is set",
        "explicitly by a test rather than left to the sweep.",
        "",
        "### What would promote a family to verified",
        "",
        "Agreement with an independent implementation on real weights: a run of the comparison sweep",
        "(`comparison/`) against TransformerLens, nnsight, vLLM or SGLang on a checkpoint of the family. The",
        "invariants above are self-consistency -- they prove the engine's points describe one coherent",
        "computation, not that the computation is the one another framework performs.",
        "",
        "## Unaudited",
        "",
        "Nothing was probed on these, so there is no claim either way -- and for most of them the likely answer",
        "is that they load. Two reasons, and they are different:",
        "",
    ]
    rows = []
    for arch in buckets[UNAUDITED]:
        report = reports.get(arch)
        status = report.status if report else "unknown"
        detail = (report.detail if report else "").split("\n")[0][:90]
        why = f"`{status}`" + (f": `{detail}`" if detail else "")
        rows.append([f"`{arch}`", why])
    out += [_table(["architecture", "why not probed"], rows), ""]
    out += [
        "- **`no_transformers_class`** -- vLLM implements the family itself and its HF checkpoints ship their",
        "  modeling code (`trust_remote_code`), so there is no class to build from a config. The eager backend",
        "  loads such checkpoints and the vLLM backend resolves against vLLM's own tree; whether either finds",
        "  its modules depends on the names, which is answerable only by downloading code or weights. Where a",
        "  family's names have been read off its checkpoint and added, that claim is checked against a synthetic",
        "  tree in `tests/test_vllm_only_families.py` -- InternLM2 is the worked example.",
        "- **`not_buildable`** -- the family's own config defaults do not survive its `__init__` (a rope field",
        "  left `None`, an attention sub-config missing `rope_theta`). A transformers-side limit, not ours: a",
        "  real checkpoint's config carries those fields, so these are likely to work.",
        "",
        "## Does not work",
        "",
        "Each of these is a *shape*, not a missing name -- adding a spelling would not help, because the",
        "canonical points do not describe what the tree does. Fixing one means deciding what a point should",
        "mean there.",
        "",
        _table(
            ["architecture", "why"],
            [
                [f"`{arch}`", fc.KNOWN_GAPS.get(arch) or (reports[arch].detail if arch in reports else "")]
                for arch in buckets[BROKEN]
            ],
        ),
        "",
        "## Keeping this current",
        "",
        "- `tests/test_models_status.py` fails when the committed doc no longer matches its sources: a new",
        "  architecture in the vLLM snapshot, a family that changed tier, a sweep checkpoint added or removed.",
        "- `tests/test_family_coverage.py` fails when a family stops resolving, and *also* when one of the three",
        '  tables above starts passing -- a fixed entry has to be deleted, so a stale "known gap" cannot',
        "  survive its own fix.",
        "- Regenerate with `PYTHONPATH=. .venv-cmp/bin/python tests/models_status.py`. Refresh the registry",
        "  snapshot from a vLLM venv after an upgrade: `.venv-vllm/bin/python tests/family_coverage.py",
        "  --refresh`.",
        "",
    ]
    return "\n".join(out)


# --- CLI ---------------------------------------------------------------------


def _refresh_architectures() -> None:
    """Rewrite the checkpoint-to-family map from the hub. Reads `config.json` only, never weights.

    Deliberately the raw file rather than ``AutoConfig``: all that is wanted is the class *name*, and
    ``AutoConfig`` on a remote-code family (EXAONE) refuses without ``trust_remote_code``, which would
    mean executing a checkpoint's code to generate documentation.
    """
    import huggingface_hub

    ids = json.loads(SWEEP.read_text())
    payload: dict[str, str] = {
        "_comment": (
            "Architecture each comparison-sweep checkpoint declares, so docs/MODELS_STATUS.md can attribute "
            "numeric verification to a family. Regenerate with "
            "`PYTHONPATH=. .venv-cmp/bin/python tests/models_status.py --refresh-architectures`."
        )
    }
    for hf_id in ids:
        config = json.loads(pathlib.Path(huggingface_hub.hf_hub_download(hf_id, "config.json")).read_text())
        architectures = config.get("architectures") or []
        if not architectures:
            raise SystemExit(f"{hf_id}: config declares no architectures")
        payload[hf_id] = architectures[0]
    ARCHITECTURES.write_text(json.dumps(payload, indent=1) + "\n")
    print(f"wrote {ARCHITECTURES}: {len(payload) - 1} checkpoints")


def build(*, allow_offline: bool = False) -> tuple[str, str]:
    """The doc and the README block, from a live audit plus the committed sweep data."""
    reports = {report.arch: report for report in fc.audit()}
    stalled = [r.arch for r in reports.values() if r.status == "needs_download"]
    if stalled and not allow_offline:
        raise SystemExit(
            f"{len(stalled)} families need the hub for a kernel and did not build ({', '.join(stalled[:4])}...). "
            "They would be written as unaudited. Rerun with HF_HUB_OFFLINE=0, or pass --allow-offline."
        )
    swept = verified_families(verified_checkpoints(), sweep_architectures())
    families = corroborated(swept)
    vllm_version = fc.snapshot().get("vllm_version", "unknown")
    return render_doc(reports, families, uncorroborated(swept), vllm_version), render_summary(
        tiers(reports, set(families)), families, vllm_version
    )


def splice_readme(block: str) -> str:
    text = README.read_text()
    body = f"{START}\n\n{block}\n\n{END}"
    if START in text and END in text:
        new = text[: text.index(START)] + body + text[text.index(END) + len(END) :]
    else:
        raise SystemExit(f"{README} has no {START} / {END} markers to splice into")
    README.write_text(new)
    return "written" if new != text else "unchanged"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh-architectures", action="store_true", help="rewrite the sweep's family map")
    parser.add_argument("--allow-offline", action="store_true", help="write even if kernel-fetching families stalled")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the committed files are stale")
    args = parser.parse_args()
    sys.path.insert(0, str(ROOT))

    if args.refresh_architectures:
        _refresh_architectures()
        raise SystemExit(0)

    doc, summary = build(allow_offline=args.allow_offline)
    if args.check:
        stale = [
            name
            for name, current, committed in (
                ("docs/MODELS_STATUS.md", doc, DOC.read_text() if DOC.exists() else ""),
                ("README.md", summary, README.read_text()),
            )
            if current not in committed and current != committed
        ]
        print("stale: " + ", ".join(stale) if stale else "up to date")
        raise SystemExit(1 if stale else 0)
    DOC.write_text(doc)
    print(f"wrote {os.path.relpath(DOC, ROOT)} and spliced README.md ({splice_readme(summary)})")
