"""Generated by api/generate.py from api/engine.yaml -- do not edit; run `uv run python api/generate.py`.

The engine's API contract: what every backend exposes. The Protocol is checked against
EagerModel and VLLMModel by tests/test_api_generated.py (signatures) and by pyright
(interp_engine/_conformance.py).
"""

from __future__ import annotations

from collections.abc import AsyncIterator, Mapping, Sequence
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

import torch

from interp_engine.address import Address

if TYPE_CHECKING:
    from interp_engine.protocol import Point
    from interp_engine.sampling import SamplingSettings
    from interp_engine.steer import GenStep

MANIFEST_VERSION = 1
MANIFEST_DIGEST = "f25bc48efa531b9a"

__all__ = [
    "DirectionSet",
    "EngineAPI",
    "EngineDescription",
    "LensSpec",
    "LensStep",
    "MANIFEST_DIGEST",
    "MANIFEST_VERSION",
]


@dataclass(frozen=True)
class EngineDescription:
    """What this model object can serve, as the object itself answers. No forward."""

    backend: str
    """The load_model backend name (eager, vllm, vllm-static, vllm-generate)."""
    hf_model_id: str
    n_layers: int
    d_model: int
    n_heads: int
    n_kv_heads: int
    head_dim: int
    hooks_available: bool
    """Whether forward hooks run, so any served point can be read or written per request."""
    graph_replay: bool
    """Whether the forward replays captured graphs, so only static taps are reachable."""
    static_points: list[Address]
    """The read taps a graph engine declared at load. Empty on a hooked engine."""
    static_writes: list[Address]
    """The write taps a graph engine declared at load. Empty on a hooked engine."""
    capture_points: list[str]
    """Canonical point names this model can capture, asked at layer 0 for per-layer points. Empty
    when nothing is capturable.
    """
    residual_readable: bool
    """Whether resid_post can be read, by a hook, a static tap or native extraction."""
    attention: bool
    """Whether the attention pair (attn_probs, attn_scores) is served."""


@dataclass(frozen=True)
class LensSpec:
    """One lens to read at every position."""

    layers: list[int]
    """The layers to read, ascending. The last is decoded as the final row of each position."""
    jacobian: bool = False
    """Whether to carry each layer through its J_bar first. A layer with no J_bar is read as it is."""
    jacobian_set: str = "default"
    """The name of the J_bar set to use, as set_lens_jacobians installed it."""


@dataclass(frozen=True)
class LensStep:
    """One position's read-out, for every LensSpec of the call in order."""

    position: int
    token_id: int
    is_generated: bool
    top_ids: list[torch.Tensor]
    """Per LensSpec, [n_layers, k] token ids, best first."""
    top_probs: list[torch.Tensor]
    """Per LensSpec, [n_layers, k] float32 probabilities over the full vocabulary."""


@dataclass(frozen=True)
class DirectionSet:
    """Directions read at one point. A probe is one direction; an SAE encoder is many, with a bias
    and a nonlinearity.
    """

    point: Address
    """Where the directions are read."""
    vectors: torch.Tensor
    """[k, width] directions, in the basis of the point's rows."""
    bias: torch.Tensor | None = None
    """[k], added to the dot products."""
    nonlinearity: str = "none"
    """none or relu, applied last."""


@runtime_checkable
class EngineAPI(Protocol):
    """The surface every backend model object satisfies."""

    @property
    def hf_model_id(self) -> str:
        """The Hugging Face repo id this was loaded from."""
        ...

    @property
    def n_layers(self) -> int:
        """Number of decoder layers."""
        ...

    @property
    def d_model(self) -> int:
        """Residual stream width."""
        ...

    @property
    def n_heads(self) -> int:
        """Number of attention query heads, for the whole model."""
        ...

    @property
    def n_kv_heads(self) -> int:
        """Number of key/value heads; fewer than n_heads under GQA or MQA."""
        ...

    @property
    def head_dim(self) -> int:
        """Width of one attention head. Not d_model // n_heads on every family."""
        ...

    @property
    def default_prepend_bos(self) -> bool:
        """Whether to_tokens prepends BOS when the caller does not say."""
        ...

    @property
    def tokenizer_prepends_bos(self) -> bool:
        """Whether the tokenizer adds BOS on its own, so a caller must not add a second one."""
        ...

    def describe(self) -> EngineDescription:
        """What this model can serve, in one record: for a server to advertise, and for a caller to
        check before it asks. Answers from the load configuration; no forward.
        """
        ...

    def refuses(self, point: Address | str | Point, layer: int | None = None) -> str | None:
        """Why this model cannot produce the point, or null when it can. No forward."""
        ...

    def serves(self, point: Address | str | Point, layer: int | None = None) -> bool:
        """Whether this model can produce the point."""
        ...

    def sampling_settings(
        self,
        *,
        temperature: float | None = None,
        top_k: int | None = None,
        top_p: float | None = None,
        presence_penalty: float | None = None,
    ) -> SamplingSettings:
        """What a generation called with these knobs runs with: a knob passed is used, a knob left
        null takes the checkpoint's recommendation, and a knob neither states is neutral.
        """
        ...

    async def capture(
        self,
        prompt_token_ids: Sequence[int],
        points: Sequence[Address | str | Point],
        *,
        steering_spec: Any = None,
        detach: bool = True,
        rows: Sequence[int] | None = None,
    ) -> dict[Address, torch.Tensor]:
        """Capture the points over one prompt's forward pass: [n_prompt_tokens, width] per address,
        no batch axis. With steering, from the steered forward.
        """
        ...

    async def project(
        self,
        prompt_token_ids: Sequence[int],
        directions: Sequence[DirectionSet],
        *,
        steering_spec: Any = None,
    ) -> list[torch.Tensor]:
        """Read each DirectionSet over one prompt's forward pass: per set, [n_prompt_tokens, k]
        float32, the rows' dot products with the vectors, plus the bias, through the
        nonlinearity. Where a worker runs the forward, it projects the rows, so only the values
        cross.
        """
        ...

    async def unembed_rows(self, token_ids: Sequence[int]) -> torch.Tensor:
        """W_U[token_ids]: the [k, d_model] residual-space directions the unembed reads."""
        ...

    async def decode_residuals(self, residuals: torch.Tensor, *, detach: bool = True) -> torch.Tensor:
        """Decode [n_rows, d_model] residuals to [n_rows, vocab] logits through the final norm, the
        unembed and the family's post-unembed arithmetic (softcap included).
        """
        ...

    async def set_lens_jacobians(self, jacobians: Mapping[int, torch.Tensor] | None, *, name: str = "default") -> int:
        """Install one [d_model, d_model] J_bar per source layer as the set name, where the read-out
        runs, for every later generate_with_lens call; null removes that set. Other sets stay.
        Returns the bytes this set holds, per rank under tensor parallelism.
        """
        ...

    def generate_with_lens(
        self,
        prompt_token_ids: Sequence[int],
        lenses: Sequence[LensSpec],
        *,
        point: str = "resid_post",
        top_n: int = 10,
        max_tokens: int = 0,
        temperature: float = 0.0,
        seed: int | None = None,
        word_mask: torch.Tensor | None = None,
        skip_before: int = 0,
        stream_reduce: str = "none",
        stream_index: int | None = None,
        jacobians: Mapping[int, torch.Tensor] | None = None,
        softcap: float | None = None,
        steering_spec: Any = None,
    ) -> AsyncIterator[LensStep]:
        """Read each lens at every prompt position, then generate max_tokens tokens and read each as
        it lands. One LensStep per position from skip_before on, in order; a stop token ends it
        after its own step. point names the tap, and stream_reduce/stream_index collapse a stream
        stack to the d_model vector the lens was fitted on. word_mask [vocab] bool ranks word ids
        only; the final layer keeps its true top-1. jacobians carries the default set's J_bar for
        this call; a Jacobian lens otherwise uses the set set_lens_jacobians installed. softcap
        is applied only where the backend's unembed does not apply one. With steering, or inside
        a steer() block, every read is of the steered forward.
        """
        ...

    def generate_steps(
        self,
        prompt_token_ids: Sequence[int],
        *,
        max_tokens: int = 64,
        temperature: float | None = None,
        top_k: int | None = None,
        top_p: float | None = None,
        presence_penalty: float | None = None,
        stop_at_eos: bool = True,
        n_logprobs: int = 0,
        seed: int | None = None,
    ) -> AsyncIterator[GenStep]:
        """One GenStep per generated token. The stop token, when sampled, is the last step."""
        ...
