"""Render ``api/engine.yaml`` into the Python source that holds every backend to it.

One output, committed, marked do-not-edit: ``interp_engine/api.py``, the ``EngineAPI`` Protocol
and the records the manifest defines.

Run it after editing the manifest::

    uv run python api/generate.py

``tests/test_api_generated.py`` fails when the committed copy is stale. The output is
deterministic, so that test compares bytes. Tooling, not part of the wheel.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "api" / "engine.yaml"
PY_OUT = ROOT / "interp_engine" / "api.py"

HEADER = "Generated by api/generate.py from api/engine.yaml -- do not edit; run `uv run python api/generate.py`."

KINDS = ("property", "sync", "async", "stream")
SCALARS = ("int", "uint64", "float", "bool", "str", "tensor", "address", "token_ids", "steering")
OP_KEYS = {"kind", "params", "returns", "doc", "cases"}
PARAM_KEYS = {"type", "positional", "default", "python_name"}
CASE_KEYS = {"name", "inputs", "compare", "fields"}
RECORD_KEYS = {"external", "doc", "fields", "python_module"}
FIELD_KEYS = {"type", "doc", "default"}


# ------------------------------------------------------------------------------------ types --


@dataclass(frozen=True)
class T:
    """A parsed manifest type: ``name`` with ``args``, optional or not."""

    name: str
    args: tuple[T, ...] = ()
    optional: bool = False

    def __str__(self) -> str:
        inner = f"{self.name}[{', '.join(map(str, self.args))}]" if self.args else self.name
        return inner + ("?" if self.optional else "")


def parse_type(text: str, known: set[str]) -> T:
    """Parse ``map[address, tensor]``, ``list[int]?`` and the like, refusing names nothing defines."""
    text = text.strip()
    optional = text.endswith("?")
    if optional:
        text = text[:-1].strip()
    m = re.fullmatch(r"(\w+)\[(.*)\]", text)
    if not m:
        if text not in SCALARS and text not in known:
            raise ValueError(f"unknown type {text!r}")
        return T(text, (), optional)
    name, body = m.group(1), m.group(2)
    parts, depth, start = [], 0, 0
    for i, ch in enumerate(body):
        depth += ch == "["
        depth -= ch == "]"
        if ch == "," and depth == 0:
            parts.append(body[start:i])
            start = i + 1
    parts.append(body[start:])
    args = tuple(parse_type(p, known) for p in parts)
    arity = {"list": 1, "map": 2, "stream": 1}
    if name not in arity or len(args) != arity[name]:
        raise ValueError(f"bad generic {text!r}")
    return T(name, args, optional)


# ---------------------------------------------------------------------------------- manifest --


@dataclass
class Param:
    name: str
    type: T
    positional: bool
    has_default: bool
    default: Any
    python_name: str


@dataclass
class Case:
    name: str
    inputs: dict[str, Any]
    compare: str
    fields: list[str] | None
    digest: str


@dataclass
class Op:
    name: str
    kind: str
    params: list[Param]
    returns: T | None
    doc: str
    cases: list[Case] = field(default_factory=list)


@dataclass
class Field:
    name: str
    type: T
    doc: str
    has_default: bool
    default: Any


@dataclass
class Record:
    name: str
    external: bool
    doc: str
    fields: list[Field]
    python_module: str | None


@dataclass
class Manifest:
    version: int
    tolerances: dict[str, dict[str, Any]]
    records: dict[str, Record]
    ops: list[Op]
    digest: str


def case_digest(op: str, case: dict[str, Any]) -> str:
    """A stable hash of one case, so a fixture written for an older case reads as stale."""
    blob = json.dumps({"op": op, **case}, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(blob.encode()).hexdigest()[:16]


def _check_keys(where: str, got: dict[str, Any], allowed: set[str]) -> None:
    extra = set(got) - allowed
    if extra:
        raise ValueError(f"{where}: unknown key(s) {sorted(extra)}")


def load(path: Path = MANIFEST) -> Manifest:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    known = set(raw.get("records", {}))
    records: dict[str, Record] = {}
    for rname, r in raw.get("records", {}).items():
        _check_keys(f"record {rname}", r, RECORD_KEYS)
        fields = []
        for fname, f in r["fields"].items():
            _check_keys(f"record {rname}.{fname}", f, FIELD_KEYS)
            fields.append(
                Field(
                    fname,
                    parse_type(f["type"], known),
                    f.get("doc", ""),
                    "default" in f,
                    f.get("default"),
                )
            )
        external = bool(r.get("external", False))
        if external and not r.get("python_module"):
            raise ValueError(f"record {rname}: an external record names its python_module")
        records[rname] = Record(rname, external, r.get("doc", ""), fields, r.get("python_module"))
    tolerances = raw.get("tolerances", {})
    ops = []
    for oname, o in raw["operations"].items():
        _check_keys(f"operation {oname}", o, OP_KEYS)
        kind = o["kind"]
        if kind not in KINDS:
            raise ValueError(f"operation {oname}: kind must be one of {KINDS}")
        params = []
        for pname, p in (o.get("params") or {}).items():
            _check_keys(f"operation {oname}.{pname}", p, PARAM_KEYS)
            params.append(
                Param(
                    pname,
                    parse_type(p["type"], known),
                    bool(p.get("positional", False)),
                    "default" in p,
                    p.get("default"),
                    p.get("python_name", pname),
                )
            )
        seen_kw = False
        for p in params:
            if not p.positional:
                seen_kw = True
            elif seen_kw:
                raise ValueError(f"operation {oname}.{p.name}: a positional parameter after a keyword one")
        cases = []
        for c in o.get("cases") or []:
            _check_keys(f"operation {oname} case", c, CASE_KEYS)
            if c["compare"] not in tolerances:
                raise ValueError(f"operation {oname} case {c['name']}: no tolerance named {c['compare']!r}")
            unknown = set(c.get("inputs") or {}) - {p.name for p in params}
            if unknown:
                raise ValueError(f"operation {oname} case {c['name']}: inputs {sorted(unknown)} are not parameters")
            cases.append(
                Case(c["name"], dict(c.get("inputs") or {}), c["compare"], c.get("fields"), case_digest(oname, c))
            )
        if kind == "property" and (params or cases):
            raise ValueError(f"operation {oname}: a property takes no params and has no cases")
        ops.append(
            Op(
                oname,
                kind,
                params,
                parse_type(o["returns"], known) if o.get("returns") else None,
                " ".join(str(o.get("doc", "")).split()),
                cases,
            )
        )
    digest = hashlib.sha256(path.read_bytes()).hexdigest()[:16]
    return Manifest(int(raw["version"]), tolerances, records, ops, digest)


# ------------------------------------------------------------------------------------ python --

PY_IN = {
    "int": "int",
    "uint64": "int",
    "float": "float",
    "bool": "bool",
    "str": "str",
    "tensor": "torch.Tensor",
    "address": "Address | str | Point",
    "token_ids": "Sequence[int]",
    "steering": "Any",
}
PY_OUT_T = {**PY_IN, "address": "Address", "token_ids": "list[int]"}


def py_type(t: T, *, inp: bool) -> str:
    table = PY_IN if inp else PY_OUT_T
    if t.name == "list":
        inner = py_type(t.args[0], inp=inp)
        s = f"Sequence[{inner}]" if inp else f"list[{inner}]"
    elif t.name == "map":
        k, v = (py_type(a, inp=inp) for a in t.args)
        s = f"Mapping[{k}, {v}]" if inp else f"dict[{k}, {v}]"
    elif t.name == "stream":
        s = f"AsyncIterator[{py_type(t.args[0], inp=False)}]"
    else:
        s = table.get(t.name, t.name)
    if t.optional and s != "Any":
        s = f"{s} | None"
    return s


def py_literal(v: Any) -> str:
    if v is None:
        return "None"
    if isinstance(v, bool):
        return "True" if v else "False"
    return repr(v)


def py_doc(text: str, indent: str) -> list[str]:
    if not text:
        return []
    words, lines, line = text.split(), [], ""
    width = 100 - len(indent) - 3
    for w in words:
        if line and len(line) + 1 + len(w) > width:
            lines.append(line)
            line = w
        else:
            line = f"{line} {w}" if line else w
    lines.append(line)
    if len(lines) == 1:
        return [f'{indent}"""{lines[0]}"""']
    return [f'{indent}"""{lines[0]}', *(f"{indent}{ln}" for ln in lines[1:]), f'{indent}"""']


def render_python(m: Manifest) -> str:
    out = [
        f'"""{HEADER}',
        "",
        "The engine's API contract: what every backend exposes. The Protocol is checked against",
        "EagerModel and VLLMModel by tests/test_api_generated.py (signatures) and by pyright",
        "(interp_engine/_conformance.py).",
        '"""',
        "",
    ]
    out += ["from __future__ import annotations", ""]
    out += ["from collections.abc import AsyncIterator, Mapping, Sequence"]
    out += [
        "from dataclasses import dataclass",
        "from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable",
        "",
    ]
    out += ["import torch", "", "from interp_engine.address import Address", ""]
    externals = sorted((r.python_module, r.name) for r in m.records.values() if r.external)
    out += ["if TYPE_CHECKING:"]
    out += ["    from interp_engine.protocol import Point"]
    for mod, name in externals:
        out.append(f"    from {mod} import {name}")
    out += ["", f"MANIFEST_VERSION = {m.version}", f'MANIFEST_DIGEST = "{m.digest}"', ""]
    names = [
        "EngineAPI",
        "MANIFEST_DIGEST",
        "MANIFEST_VERSION",
        *sorted(r.name for r in m.records.values() if not r.external),
    ]
    out += [f"__all__ = {json.dumps(sorted(names))}", ""]
    for r in m.records.values():
        if r.external:
            continue
        out += ["", "@dataclass(frozen=True)", f"class {r.name}:"]
        out += py_doc(r.doc, "    ") or ['    """"""']
        out.append("")
        for f in r.fields:
            default = f" = {py_literal(f.default)}" if f.has_default else ""
            out.append(f"    {f.name}: {py_type(f.type, inp=False)}{default}")
            out += py_doc(f.doc, "    ")
    out += ["", "", "@runtime_checkable", "class EngineAPI(Protocol):"]
    out += py_doc("The surface every backend model object satisfies.", "    ")
    for op in m.ops:
        out.append("")
        if op.kind == "property":
            out += ["    @property", f"    def {op.name}(self) -> {py_type(op.returns, inp=False)}:"]  # type: ignore[arg-type]
            out += py_doc(op.doc, "        ")
            out.append("        ...")
            continue
        params = op.params
        sig = ["self"]
        star = False
        for p in params:
            if not p.positional and not star:
                sig.append("*")
                star = True
            default = f" = {py_literal(p.default)}" if p.has_default else ""
            sig.append(f"{p.python_name}: {py_type(p.type, inp=True)}{default}")
        ret = py_type(op.returns, inp=False) if op.returns else "None"
        prefix = "async def" if op.kind == "async" else "def"
        line = f"    {prefix} {op.name}({', '.join(sig)}) -> {ret}:"
        if len(line) <= 120:
            out.append(line)
        else:
            out.append(f"    {prefix} {op.name}(")
            out += [f"        {s}," for s in sig]
            out.append(f"    ) -> {ret}:")
        out += py_doc(op.doc, "        ")
        out.append("        ...")
    out.append("")
    return "\n".join(out)


# ----------------------------------------------------------------------------------- driver --


def ruff_format(text: str, path: Path) -> str:
    """``text`` with unused imports dropped and formatted as the pre-commit hook's ``ruff format``
    would leave it, so the generator, the hook and CI's lint gate never disagree."""
    ruff = [sys.executable, "-m", "ruff"]
    stdin = ["--stdin-filename", str(path), "-"]
    run = {"capture_output": True, "text": True, "cwd": ROOT, "check": True}
    text = subprocess.run(
        [*ruff, "check", "--fix", "--select", "F401,I001", "--exit-zero", *stdin], input=text, **run
    ).stdout
    return subprocess.run([*ruff, "format", *stdin], input=text, **run).stdout


def outputs() -> dict[Path, str]:
    m = load()
    return {
        PY_OUT: ruff_format(render_python(m), PY_OUT),
    }


def write() -> list[Path]:
    written = []
    for path, text in outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            written.append(path)
    return written


def stale() -> list[Path]:
    return [p for p, text in outputs().items() if not p.exists() or p.read_text(encoding="utf-8") != text]


if __name__ == "__main__":
    if "--check" in sys.argv[1:]:
        if paths := stale():
            for path in paths:
                print(f"stale: {path.relative_to(ROOT)}; run `make api`", file=sys.stderr)
            sys.exit(1)
        sys.exit(0)
    for path in write():
        print(f"wrote {path.relative_to(ROOT)}")
    sys.exit(0)
